"""
Django settings for Generator project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# .env: в папке Generator/ или в корне проекта (например /opt/generator/.env)
load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR.parent / ".env")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# В production задайте SECRET_KEY через переменную окружения
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-)&u-i%%%7kr6y6kx11pcr$fq6e1ita5)%ykv1aluxmvtbaln#7')

# Общий секрет с ЛК для JWT входа в урок (/lesson/join/). В .env: LESSON_SECRET=...
LESSON_SECRET = os.environ.get("LESSON_SECRET", "").strip()
# Тот же секрет, что LESSON_WEBHOOK_SECRET в ЛК — заголовок X-Lesson-Webhook-Secret при POST /api/lesson/teacher-joined/
# Если пусто, при уведомлении ЛК подставляется LESSON_SECRET (удобно, когда в ЛК проверяют тот же ключ, что и у JWT).
LESSON_WEBHOOK_SECRET = os.environ.get("LESSON_WEBHOOK_SECRET", "").strip()

# Свой сервер Jitsi (meet.example.com) — через запятую, нижний регистр не обязателен.
# Нужно, чтобы во встроенный iframe подставлялись параметры config.* (см. views.enhance_jitsi_iframe_url).
JITSI_EMBED_EXTRA_HOSTS = tuple(
    h.strip().lower()
    for h in os.environ.get("JITSI_EMBED_EXTRA_HOSTS", "").split(",")
    if h.strip()
)
# Для генерации Jitsi JWT (moderator=true для учителя) на своём сервере:
# значения берутся из prosody config — luaModules/lib-jitsi-meet/token/prosody.cfg.lua (app_id / app_secret).
JITSI_APP_ID = os.environ.get("JITSI_APP_ID", "").strip()
JITSI_APP_SECRET = os.environ.get("JITSI_APP_SECRET", "").strip()

LK_PUBLIC_URL = os.environ.get("LK_PUBLIC_URL", "https://lk.genurok.tw1.ru").rstrip("/")
# Базовый API-URL личного кабинета для server-to-server запросов генератора.
# Если не задан, используем LK_PUBLIC_URL для обратной совместимости.
CABINET_API_BASE = (
    os.environ.get("CABINET_API_BASE", "").strip().rstrip("/")
    or LK_PUBLIC_URL
)
# Полный URL страницы после входа (дашборд). Если пусто — кнопка «Личный кабинет» ведёт на LK_PUBLIC_URL.
# Пример: http://lk.example.com/dashboard или http://lk.example.com/app/
LK_DASHBOARD_URL = os.environ.get("LK_DASHBOARD_URL", "").strip().rstrip("/")
# Явный URL POST при входе учителя в звонок (иначе LK_PUBLIC_URL + /api/lesson/teacher-joined/).
# ЛК по этому вызову шлёт ученику приглашение на все устройства (WS + web-push и т.д.).
LK_LESSON_NOTIFY_URL = os.environ.get("LK_LESSON_NOTIFY_URL", "").strip()
# POST при открытии комнаты учеником на генераторе (иначе LK_PUBLIC_URL + /api/lesson/student-joined/).
# Тот же X-Lesson-Webhook-Secret, что для teacher-joined.
LK_LESSON_STUDENT_NOTIFY_URL = os.environ.get("LK_LESSON_STUDENT_NOTIFY_URL", "").strip()
# POST при завершении урока — отчёт «Урок» в ЛК (иначе LK_PUBLIC_URL + /api/lesson/teacher-left/).
LK_LESSON_TEACHER_LEFT_URL = os.environ.get("LK_LESSON_TEACHER_LEFT_URL", "").strip()
# Кнопка «Личный кабинет»: если переменная не задана — пароль 100326; пустая строка LK_NAVIGATION_PASSWORD= — без пароля.
_lk_nav_env = os.environ.get("LK_NAVIGATION_PASSWORD")

TASKS_GET_SECRET = os.environ.get("LINK_SECRET_FOR_TASKS", "").strip()



if _lk_nav_env is None:
    LK_NAVIGATION_PASSWORD = "100326"
else:
    LK_NAVIGATION_PASSWORD = _lk_nav_env.strip()

DEBUG = os.environ.get('DEBUG', 'true').lower() == 'true'
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()] or ["*"]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'Generator.apps.GeneratorConfig',
    'Board',
    'corsheaders',
    "django_ckeditor_5",
]
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "bold", "italic",
            "link",
            "bulletedList", "numberedList",
            "imageUpload",
            "undo", "redo"
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "imageStyle:full",
                "imageStyle:side"
            ]
        },
    }
}
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 2. Session — до Common
    "django.middleware.common.CommonMiddleware",  # 3. Common — один раз
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Разрешаем встраивать страницы в iframe на том же origin
# (нужно для /lesson/join/ -> iframe с /<level>/<subject>/variant/<id>/).
X_FRAME_OPTIONS = "SAMEORIGIN"

# Прод: задайте CORS_ALLOWED_ORIGINS=https://гегенератор,https://лк (через запятую) — иначе по умолчанию разрешены все origin (только для разработки).
_cors_allowed_list = [o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]
if _cors_allowed_list:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _cors_allowed_list
else:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

_extra_origins_raw = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
_extra_origins = [o.strip() for o in _extra_origins_raw.split(',') if o.strip()]

# Если CSRF_TRUSTED_ORIGINS не задан — строим доверенные origins из DJANGO_ALLOWED_HOSTS автоматически.
# Это позволяет не дублировать домен: достаточно задать только DJANGO_ALLOWED_HOSTS=tes.genurok.ru,...
if not _extra_origins:
    _allowed_hosts_raw = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
    for _h in _allowed_hosts_raw.split(','):
        _h = _h.strip()
        if _h and _h != '*' and not _h.startswith('.'):
            _extra_origins.append(f"https://{_h}")
            _extra_origins.append(f"http://{_h}")

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://localhost:5001",
    "http://127.0.0.1:5001",
    # ЛК локально
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
    "https://*.replit.dev",
    "https://*.repl.co",
] + _extra_origins

CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # React должен читать cookie
SESSION_COOKIE_SAMESITE = 'Lax'

# Django за nginx: сообщаем, что оригинальный запрос — HTTPS (X-Forwarded-Proto пробрасывает nginx)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ROOT_URLCONF = 'Generator.urls'

FRONTEND_DIR = Path(__file__).resolve().parent.parent.parent / 'frontend' / 'dist'
# frontend/dist появляется после npm run build
TEMPLATE_DIRS = [FRONTEND_DIR] if FRONTEND_DIR.exists() else []

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    }
]

WSGI_APPLICATION = 'Generator.wsgi.application'
ASGI_APPLICATION = "Generator.asgi.application"

# WebSocket уроков: redis — для нескольких воркеров; inmemory — один процесс Daphne, Redis не нужен.
_channel_backend = (os.environ.get("CHANNEL_LAYER_BACKEND") or "redis").strip().lower()
if _channel_backend in ("inmemory", "memory", "local"):
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
else:
    _redis_host = os.environ.get("REDIS_HOST", "127.0.0.1")
    _redis_port = int(os.environ.get("REDIS_PORT", "6379"))
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [(_redis_host, _redis_port)]},
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# В systemd задают PGDATABASE/PGUSER/... — обязательно читаем их (раньше были захардкожены generatordb).
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("PGDATABASE", "generatordb"),
#         "USER": os.environ.get("PGUSER", "generator_user"),
#         "PASSWORD": os.environ.get("PGPASSWORD", "StrongPass123"),
#         "HOST": os.environ.get("PGHOST", "localhost"),
#         "PORT": os.environ.get("PGPORT", "5432"),
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("PGDATABASE", "generatordb"),
        "USER": os.environ.get("PGUSER", "postgres"),
        "PASSWORD": os.environ.get("PGPASSWORD", "postgres"),
        "HOST": os.environ.get("PGHOST", "localhost"),
        "PORT": os.environ.get("PGPORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"] + ([FRONTEND_DIR] if FRONTEND_DIR.exists() else [])
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
# После выхода из админки — на публичную главную (не «/» текущего хоста: на dev это localhost).
_gen_home = os.environ.get("GENUROK_PUBLIC_HOME_URL", "http://genurok.ru").strip().rstrip("/")
GENUROK_PUBLIC_HOME_URL = f"{_gen_home}/"
LOGOUT_REDIRECT_URL = GENUROK_PUBLIC_HOME_URL

# Telegram bot для отправки сообщений об ошибках
# Для группового чата: добавьте бота в группу, затем получите ID через
# https://api.telegram.org/bot<TOKEN>/getUpdates после сообщения в группе.
# ID группы — отрицательное число, например: -1001234567890
# TELEGRAM_TOPIC_ID — ID топика (для групп с темами). Число из URL топика.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '')
TELEGRAM_TOPIC_ID = os.environ.get('TELEGRAM_TOPIC_ID', '') or None  # опционально

# —— HTTPS / cookies (прод, DEBUG=false): редирект HTTP→HTTPS обычно в nginx; Django может дублировать — осторожно с петлёй.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "false").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )
    SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "true").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )
    CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "true").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )
