"""
Django settings for Generator project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

# .env: в папке Generator/ или в корне проекта (например /opt/generator/.env)
# override=True — чтобы пароли с "#" из файла не перекрывались старым env shell
load_dotenv(BASE_DIR / ".env", override=True)
load_dotenv(BASE_DIR.parent / ".env", override=True)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

_TESTING_NESTED = "test" in sys.argv
DEBUG = _TESTING_NESTED or os.environ.get('DEBUG', 'false').lower() == 'true'

# В production задайте SECRET_KEY через переменную окружения
_secret_nested = (os.environ.get('SECRET_KEY') or os.environ.get('DJANGO_SECRET_KEY') or '').strip()
_DEV_NESTED = 'django-insecure-nested-dev-only'
if DEBUG or _TESTING_NESTED:
    SECRET_KEY = _secret_nested or _DEV_NESTED
else:
    from django.core.exceptions import ImproperlyConfigured
    if not _secret_nested or _secret_nested == _DEV_NESTED:
        raise ImproperlyConfigured('Set SECRET_KEY or DJANGO_SECRET_KEY in production.')
    SECRET_KEY = _secret_nested

# Общий секрет с ЛК для JWT входа в урок (/lesson/join/). В .env: LESSON_SECRET=...
LESSON_SECRET = os.environ.get("LESSON_SECRET", "").strip()
# Тот же секрет, что LESSON_WEBHOOK_SECRET в ЛК — заголовок X-Lesson-Webhook-Secret при POST /api/lesson/teacher-joined/
# Если пусто, при уведомлении ЛК подставляется LESSON_SECRET (удобно, когда в ЛК проверяют тот же ключ, что и у JWT).
LESSON_WEBHOOK_SECRET = os.environ.get("LESSON_WEBHOOK_SECRET", "").strip()

# Свой сервер Jitsi (meet.example.com) — через запятую, нижний регистр не обязателен.
# Нужно, чтобы во встроенный iframe подставлялись параметры config.* (см. views.enhance_jitsi_iframe_url).
JITSI_EMBED_EXTRA_HOSTS = tuple(
    h.strip().lower()
    for h in os.environ.get("JITSI_EMBED_EXTRA_HOSTS", "").split(",")
    if h.strip()
)
# Видеоуроки в кабинете + JWT для собственного Jitsi (см. docs/JITSI_INTEGRATION.md).
JITSI_DOMAIN = os.environ.get("JITSI_DOMAIN", "meet.jit.si").strip() or "meet.jit.si"
JITSI_AUTH_MODE = (os.environ.get("JITSI_AUTH_MODE", "none") or "none").strip().lower()
JITSI_APP_ID = os.environ.get("JITSI_APP_ID", "").strip()
JITSI_APP_SECRET = os.environ.get("JITSI_APP_SECRET", "").strip()
JITSI_SUB = os.environ.get("JITSI_SUB", "").strip()
JITSI_AUD = os.environ.get("JITSI_AUD", "jitsi").strip() or "jitsi"
try:
    JITSI_TOKEN_TTL_SECONDS = int(os.environ.get("JITSI_TOKEN_TTL_SECONDS", "7200") or "7200")
except ValueError:
    JITSI_TOKEN_TTL_SECONDS = 7200
try:
    JITSI_JOIN_BEFORE_MINUTES = int(os.environ.get("JITSI_JOIN_BEFORE_MINUTES", "15") or "15")
except ValueError:
    JITSI_JOIN_BEFORE_MINUTES = 15
try:
    JITSI_JOIN_AFTER_MINUTES = int(os.environ.get("JITSI_JOIN_AFTER_MINUTES", "30") or "30")
except ValueError:
    JITSI_JOIN_AFTER_MINUTES = 30

LK_PUBLIC_URL = os.environ.get("LK_PUBLIC_URL", "https://itflux-academy.ru").rstrip("/")
# Базовый API-URL личного кабинета для server-to-server запросов генератора.
# Если не задан, используем LK_PUBLIC_URL для обратной совместимости.
CABINET_API_BASE = (
    os.environ.get("CABINET_API_BASE", "").strip().rstrip("/")
    or LK_PUBLIC_URL
)
# Email учителей, которые могут публиковать планы в общий каталог «Готовые».
LESSON_PLAN_CATALOG_PUBLISHER_EMAILS = tuple(
    email.strip().lower()
    for email in os.environ.get(
        "LESSON_PLAN_CATALOG_PUBLISHER_EMAILS",
        "dv_sorokina@mail.ru",
    ).split(",")
    if email.strip()
)
# Usernames that can edit task tags on «Все задачи».
TASK_TAG_EDITOR_USERNAMES = tuple(
    name.strip().lower()
    for name in os.environ.get(
        "TASK_TAG_EDITOR_USERNAMES",
        "darsorokinaa,admin_dasha",
    ).split(",")
    if name.strip()
)
# Полный URL страницы после входа (дашборд). Если пусто — кнопка «Личный кабинет» ведёт на LK_PUBLIC_URL.
# Пример: http://lk.example.com/dashboard или http://lk.example.com/app/
LK_DASHBOARD_URL = os.environ.get("LK_DASHBOARD_URL", "").strip().rstrip("/")
# Явный URL POST при входе учителя в звонок (иначе LK_PUBLIC_URL + /api/lesson/teacher-joined/).
# ЛК по этому вызову шлёт ученику приглашение на все устройства (WS + web-push и т.д.).
LK_LESSON_NOTIFY_URL = os.environ.get("LK_LESSON_NOTIFY_URL", "").strip()
# POST при открытии комнаты учеником на генераторе (иначе LK_PUBLIC_URL + /api/lesson/student-joined/).
# Тот же X-Lesson-Webhook-Secret, что для teacher-joined.
LK_LESSON_STUDENT_NOTIFY_URL = os.environ.get("LK_LESSON_STUDENT_NOTIFY_URL", "").strip()
# POST при завершении урока — отчёт «Урок» в ЛК (иначе LK_PUBLIC_URL + /api/lesson/teacher-left/).
LK_LESSON_TEACHER_LEFT_URL = os.environ.get("LK_LESSON_TEACHER_LEFT_URL", "").strip()
# Кнопка «Личный кабинет»: если переменная не задана — пароль 100326; пустая строка LK_NAVIGATION_PASSWORD= — без пароля.
_lk_nav_env = os.environ.get("LK_NAVIGATION_PASSWORD")

TASKS_GET_SECRET = os.environ.get("LINK_SECRET_FOR_TASKS", "").strip()

# Яндекс Телемост — создание видеовстреч из кабинета.
YANDEX_TELEMOST_CLIENT_ID = os.environ.get(
    "YANDEX_TELEMOST_CLIENT_ID",
    "21e10d82239446508ab6f2417c596fa2",
).strip()
YANDEX_TELEMOST_CLIENT_SECRET = os.environ.get("YANDEX_TELEMOST_CLIENT_SECRET", "").strip()
YANDEX_TELEMOST_OAUTH_TOKEN = os.environ.get("YANDEX_TELEMOST_OAUTH_TOKEN", "").strip()
YANDEX_TELEMOST_REFRESH_TOKEN = os.environ.get("YANDEX_TELEMOST_REFRESH_TOKEN", "").strip()
YANDEX_TELEMOST_AUTH_CODE = os.environ.get("YANDEX_TELEMOST_AUTH_CODE", "").strip()
YANDEX_TELEMOST_REDIRECT_URI = os.environ.get(
    "YANDEX_TELEMOST_REDIRECT_URI",
    "https://oauth.yandex.ru/verification_code",
).strip()
YANDEX_ACCOUNT_EMAIL = os.environ.get(
    "YANDEX_ACCOUNT_EMAIL",
    "darvitol.s@yandex.ru",
).strip()
YANDEX_TELEMOST_COHOST_EMAIL = os.environ.get(
    "YANDEX_TELEMOST_COHOST_EMAIL",
    YANDEX_ACCOUNT_EMAIL,
).strip()
YANDEX_TELEMOST_ALLOW_WEB_FALLBACK = os.environ.get(
    "YANDEX_TELEMOST_ALLOW_WEB_FALLBACK", "true"
).strip().lower() not in ("0", "false", "no", "off")
YANDEX_TELEMOST_WEB_FALLBACK_URL = os.environ.get(
    "YANDEX_TELEMOST_WEB_FALLBACK_URL",
    "https://telemost.yandex.ru/",
).strip()
YANDEX_OAUTH_SCOPES = os.environ.get("YANDEX_OAUTH_SCOPES", "").strip()
YANDEX_CALENDAR_ENABLED = os.environ.get(
    "YANDEX_CALENDAR_ENABLED", "false"
).strip().lower() not in ("0", "false", "no", "off")
YANDEX_CALENDAR_LAYER_IDS = os.environ.get("YANDEX_CALENDAR_LAYER_IDS", "").strip()
YANDEX_CALENDAR_TZ_ID = os.environ.get("YANDEX_CALENDAR_TZ_ID", "Europe/Moscow").strip()
YANDEX_CALENDAR_EMBED_URL = os.environ.get("YANDEX_CALENDAR_EMBED_URL", "").strip()
YANDEX_TELEMOST_AUTO_CREATE = os.environ.get(
    "YANDEX_TELEMOST_AUTO_CREATE", "true"
).strip().lower() not in ("0", "false", "no", "off")


if _lk_nav_env is None:
    LK_NAVIGATION_PASSWORD = ""
else:
    LK_NAVIGATION_PASSWORD = _lk_nav_env.strip()

import sys as _sys
if _lk_nav_env is None:
    LK_NAVIGATION_PASSWORD = ""
else:
    LK_NAVIGATION_PASSWORD = _lk_nav_env.strip()

_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
_hosts_n = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip() and h.strip() != '*']
if DEBUG or _TESTING_NESTED:
    ALLOWED_HOSTS = _hosts_n or ["localhost", "127.0.0.1", "testserver"]
else:
    ALLOWED_HOSTS = _hosts_n or []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'rest_framework',
    'channels',
    'Generator.apps.GeneratorConfig',
    'Board',
    'Cabinet.apps.CabinetConfig',
    'corsheaders',
    "django_ckeditor_5",
]
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "bold", "italic",
            "link",
            "bulletedList", "numberedList",
            "imageUpload",
            "undo", "redo"
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "imageStyle:full",
                "imageStyle:side"
            ]
        },
        # Сохраняем вложенные таблицы ФИПИ (математика: условие + 1) 2) …) при правке в админке.
        # Красивые карточки на сайте строятся при показе (MathContent), не в этом поле.
        "htmlSupport": {
            "allow": [
                {"name": "div", "attributes": True, "classes": True, "styles": True},
                {"name": "span", "attributes": True, "classes": True, "styles": True},
                {"name": "figure", "attributes": True, "classes": True, "styles": True},
                {
                    "name": r"^(table|tbody|thead|tfoot|tr|td|th|colgroup|col|caption)$",
                    "attributes": True,
                    "classes": True,
                    "styles": True,
                },
                {"name": "br"},
                {"name": "b"},
                {"name": "strong"},
            ],
            "disallow": [
                {"name": "div", "classes": ["oge-math-choice-task"]},
            ],
        },
    }
}
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 2. Session — до Common
    "django.middleware.common.CommonMiddleware",  # 3. Common — один раз
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "Generator.middleware.NoStoreApiMiddleware",
    "Generator.middleware.MinimumClientVersionMiddleware",
]

# Django admin TOTP (python manage.py setup_admin_totp <user>)
_admin_otp = (os.environ.get("ADMIN_OTP_REQUIRED") or "").strip().lower()
if _admin_otp in ("1", "true", "yes", "on"):
    ADMIN_OTP_REQUIRED = True
elif _admin_otp in ("0", "false", "no", "off"):
    ADMIN_OTP_REQUIRED = False
else:
    ADMIN_OTP_REQUIRED = not DEBUG

# Разрешаем встраивать страницы в iframe на том же origin
# (нужно для /lesson/join/ -> iframe с /<level>/<subject>/variant/<id>/).
X_FRAME_OPTIONS = "SAMEORIGIN"

# Прод: задайте CORS_ALLOWED_ORIGINS=https://гегенератор,https://лк (через запятую) — иначе по умолчанию разрешены все origin (только для разработки).
_cors_allowed_list = [o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]
if _cors_allowed_list:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _cors_allowed_list
elif DEBUG:
    CORS_ALLOW_ALL_ORIGINS = False
    # Vite в репо: 5001 (и иногда 5000 / 5173). CSRF_TRUSTED_ORIGINS уже включает эти порты.
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5000",
        "http://127.0.0.1:5000",
        "http://localhost:5001",
        "http://127.0.0.1:5001",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]
else:
    # Никогда не открываем все origin в production по умолчанию.
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = []

CORS_ALLOW_CREDENTIALS = True

_extra_origins_raw = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
_extra_origins = [o.strip() for o in _extra_origins_raw.split(',') if o.strip()]

# Если CSRF_TRUSTED_ORIGINS не задан — строим доверенные origins из DJANGO_ALLOWED_HOSTS автоматически.
# Это позволяет не дублировать домен: достаточно задать только DJANGO_ALLOWED_HOSTS=tes.itflux.ru,...
if not _extra_origins:
    _allowed_hosts_raw = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
    for _h in _allowed_hosts_raw.split(','):
        _h = _h.strip()
        if _h and _h != '*' and not _h.startswith('.'):
            _extra_origins.append(f"https://{_h}")
            _extra_origins.append(f"http://{_h}")

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://localhost:5001",
    "http://127.0.0.1:5001",
    # ЛК локально
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
    "https://*.replit.dev",
    "https://*.repl.co",
] + _extra_origins

CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # React должен читать cookie
SESSION_COOKIE_SAMESITE = 'Lax'

# Django за nginx: сообщаем, что оригинальный запрос — HTTPS (X-Forwarded-Proto пробрасывает nginx)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ROOT_URLCONF = 'Generator.urls'

FRONTEND_DIR = Path(__file__).resolve().parent.parent.parent / 'frontend' / 'dist'
# frontend/dist появляется после npm run build
TEMPLATE_DIRS = [FRONTEND_DIR] if FRONTEND_DIR.exists() else []

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    }
]

WSGI_APPLICATION = 'Generator.wsgi.application'
ASGI_APPLICATION = "Generator.asgi.application"

# WebSocket уроков: redis — для нескольких воркеров; inmemory — один процесс Daphne, Redis не нужен.
_channel_backend = (os.environ.get("CHANNEL_LAYER_BACKEND") or "redis").strip().lower()
if _channel_backend in ("inmemory", "memory", "local"):
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
else:
    _redis_host = os.environ.get("REDIS_HOST", "127.0.0.1")
    _redis_port = int(os.environ.get("REDIS_PORT", "6379"))
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [(_redis_host, _redis_port)]},
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# В systemd задают PGDATABASE/PGUSER/... — обязательно читаем их (раньше были захардкожены generatordb).
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("PGDATABASE", "itflux"),
#         "USER": os.environ.get("PGUSER", "generator_user"),
#         "PASSWORD": os.environ.get("PGPASSWORD", "StrongPass123"),
#         "HOST": os.environ.get("PGHOST", "localhost"),
#         "PORT": os.environ.get("PGPORT", "5432"),
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("PGDATABASE", "itflux"),
        "USER": os.environ.get("PGUSER", "postgres"),
        "PASSWORD": os.environ.get("PGPASSWORD", "postgres"),
        "HOST": os.environ.get("PGHOST", "localhost"),
        "PORT": os.environ.get("PGPORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"] + ([FRONTEND_DIR] if FRONTEND_DIR.exists() else [])
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
# После выхода из админки — на публичную главную (не «/» текущего хоста: на dev это localhost).
_gen_home = os.environ.get("ITFLUX_PUBLIC_HOME_URL", "https://itflux-academy.ru").strip().rstrip("/")
ITFLUX_PUBLIC_HOME_URL = f"{_gen_home}/"
LOGOUT_REDIRECT_URL = ITFLUX_PUBLIC_HOME_URL

# Telegram bot для отправки сообщений об ошибках.
# Отправляем только одному пользователю в личку (TELEGRAM_CHAT_ID = его user_id).
# Переменные окружения, если заданы, переопределяют значения по умолчанию.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '').strip()
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '').strip()
# Для личных чатов топиков нет — оставляем None, чтобы не отправлять message_thread_id.
TELEGRAM_TOPIC_ID = os.environ.get('TELEGRAM_TOPIC_ID', '') or None
# Публичный username бота без @ — для deep-link t.me/<bot>?start=<token>
TELEGRAM_BOT_USERNAME = os.environ.get('TELEGRAM_BOT_USERNAME', '').strip().lstrip('@')
# Секрет для Telegram webhook (заголовок X-Telegram-Bot-Api-Secret-Token)
TELEGRAM_WEBHOOK_SECRET = os.environ.get('TELEGRAM_WEBHOOK_SECRET', '').strip()

# Сообщения об ошибках в заданиях — мгновенное уведомление на почту
ERROR_REPORT_NOTIFY_EMAIL = os.environ.get(
    'ERROR_REPORT_NOTIFY_EMAIL',
    'itflux.academy@yandex.ru',
).strip()

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.yandex.ru').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'true').lower() in (
    '1', 'true', 'yes', 'on',
)
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'false').lower() in (
    '1', 'true', 'yes', 'on',
)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').strip()
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or ERROR_REPORT_NOTIFY_EMAIL,
).strip()

# —— HTTPS / cookies (прод, DEBUG=false): редирект HTTP→HTTPS обычно в nginx; Django может дублировать — осторожно с петлёй.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "false").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )
    SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "true").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )
    CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "true").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )

# —— Подписка платформы (SaaS). Не путать с биллингом учеников.
# Оплата тарифов: PAYMENTS_ENABLED=true|false (см. Generator/.env).
_PAYMENTS_ENABLED_RAW = (os.environ.get("PAYMENTS_ENABLED") or "false").strip().lower()
PAYMENTS_ENABLED = _PAYMENTS_ENABLED_RAW in ("1", "true", "yes", "on")
PAYMENT_PROVIDER = (os.environ.get("PAYMENT_PROVIDER") or "mock").strip()
PAYMENT_SECRET_KEY = (os.environ.get("PAYMENT_SECRET_KEY") or "").strip()
PAYMENT_SHOP_ID = (os.environ.get("PAYMENT_SHOP_ID") or "").strip()
# Т-Банк интернет-эквайринг (платёжная форма банка)
# https://developer.tbank.ru/eacq/scenarios/payments/nonPCI/
def _env_cred(value: str) -> str:
    value = (value or "").strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1].strip()
    return value

TBANK_TERMINAL_KEY = _env_cred(os.environ.get("TBANK_TERMINAL_KEY") or PAYMENT_SHOP_ID or "")
TBANK_PASSWORD = _env_cred(os.environ.get("TBANK_PASSWORD") or PAYMENT_SECRET_KEY or "")
TBANK_API_URL = (os.environ.get("TBANK_API_URL") or "https://securepay.tinkoff.ru/v2").rstrip("/")
TBANK_SUCCESS_URL = (os.environ.get("TBANK_SUCCESS_URL") or "").strip()
TBANK_FAIL_URL = (os.environ.get("TBANK_FAIL_URL") or "").strip()
TBANK_NOTIFICATION_URL = (os.environ.get("TBANK_NOTIFICATION_URL") or "").strip()
# false — только для локальной отладки при SSL-перехвате (антивирус/прокси)
_TBANK_VERIFY_RAW = (os.environ.get("TBANK_VERIFY_SSL") or "true").strip().lower()
TBANK_VERIFY_SSL = _TBANK_VERIFY_RAW not in ("0", "false", "no", "off")
# Чек (Receipt) в Init — для онлайн-кассы и тестового сценария Т-Банка
TBANK_TAXATION = (os.environ.get("TBANK_TAXATION") or "usn_income").strip().lower()
TBANK_VAT = (os.environ.get("TBANK_VAT") or "none").strip().lower()
TBANK_FFD_VERSION = (os.environ.get("TBANK_FFD_VERSION") or "1.05").strip()
TBANK_RECEIPT_EMAIL = (os.environ.get("TBANK_RECEIPT_EMAIL") or "").strip()
ANON_VARIANTS_MONTHLY_LIMIT = int(os.environ.get("ANON_VARIANTS_MONTHLY_LIMIT", "5"))
ANON_WORKBOOKS_MONTHLY_LIMIT = int(os.environ.get("ANON_WORKBOOKS_MONTHLY_LIMIT", "3"))

# Web Push (VAPID). Generate with: python -c "from py_vapid import Vapid01; ..."
# or leave empty — push UI will show that the channel is not configured yet.
VAPID_PUBLIC_KEY = (os.environ.get("VAPID_PUBLIC_KEY") or "").strip()
VAPID_PRIVATE_KEY = (os.environ.get("VAPID_PRIVATE_KEY") or "").strip()
VAPID_ADMIN_EMAIL = (os.environ.get("VAPID_ADMIN_EMAIL") or "mailto:admin@itflux.ru").strip()
