# Generated by Django 5.2.11 on 2026-02-27 23:30

import datetime
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('level_rus', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_short', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='Экзамен', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_template', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Task text')),
                ('files', models.FileField(blank=True, null=True, upload_to='task_files')),
                ('answer', models.TextField()),
                ('author', models.TextField(blank=True, max_length=500, null=True)),
                ('added_at', models.DateTimeField(default=datetime.datetime.today)),
                ('created_by', models.CharField(default='ADMIN')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', related_query_name='task_item', to='Generator.tagslist')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='Generator.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
            options={
                'verbose_name': 'Группа заданий',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField()),
                ('task_title', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.level')),
                ('part', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.part')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.tasklist'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('created_by', models.CharField(default='ADMIN', max_length=100)),
                ('share_token', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.JSONField(blank=True, default=dict, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.level')),
                ('var_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
        ),
        migrations.CreateModel(
            name='VariantContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.task')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.variant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LinkedTaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_numbers', models.JSONField(default=list)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
            options={
                'verbose_name': 'Связанная группа номеров',
                'unique_together': {('subject', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TaskGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.task')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.taskgroup')),
            ],
            options={
                'verbose_name': 'Задание в группе',
                'ordering': ['task_number'],
                'unique_together': {('task_group', 'task_number')},
            },
        ),
    ]
