# Generated by Django 5.2.11 on 2026-02-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_short',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
