# Generated by Django 5.2.11 on 2026-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_add_indexes_level_subject'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskgroup',
            index=models.Index(fields=['subject', 'level'], name='taskgroup_subject_level_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['subject', 'level'], name='tasklist_subject_level_idx'),
        ),
        migrations.AddIndex(
            model_name='variantcontent',
            index=models.Index(fields=['variant', 'order'], name='vc_variant_order_idx'),
        ),
    ]
