# Generated by Django 5.2.11 on 2026-02-28 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0003_add_composite_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='variant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
