# Generated by Django 5.2.11 on 2026-03-02 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0004_use_timezone_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='added_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.CharField(db_index=True, default='ADMIN'),
        ),
    ]
