# Generated by Django 5.2.11 on 2026-03-03 14:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0005_add_task_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Ответ'),
        ),
    ]
