# Generated by Django 5.2.11 on 2026-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0006_alter_task_answer_ckeditor5'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
    ]
