# Generated by Django 5.2.11 on 2026-03-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0008_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Баллы тестовые-вторичные'},
        ),
    ]
