# Generated by Django 5.2.11 on 2026-03-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0009_alter_mark_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.level'),
        ),
    ]
