# Generated by Django 5.2.11 on 2026-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0010_mark_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Комментарий к баллу',
            },
        ),
    ]
