# Generated by Django 5.2.11 on 2026-03-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0011_markcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
    ]
