# Generated by Django 5.2.11 on 2026-03-13 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0012_task_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.markcomment'),
        ),
    ]
