# Generated by Django 5.2.11 on 2026-03-13 20:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0014_supportinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_preview_text', django_ckeditor_5.fields.CKEditor5Field()),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.level')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.part')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
            options={
                'verbose_name': 'Текст перед задачами',
            },
        ),
    ]
