# Generated by Django 5.2.11 on 2026-03-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0015_taskpreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_type_text', models.CharField()),
            ],
            options={
                'verbose_name': 'Подсказки к заданиям',
            },
        ),
        migrations.AddField(
            model_name='taskpreview',
            name='preview_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.previewtype'),
        ),
    ]
