# Generated by Django 5.2.11 on 2026-03-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0016_previewtype_taskpreview_preview_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previewtype',
            options={'verbose_name': 'Тип подсказки'},
        ),
        migrations.AlterModelOptions(
            name='supportinfo',
            options={'verbose_name': 'Справочная информация'},
        ),
        migrations.AddField(
            model_name='mark',
            name='score_level',
            field=models.CharField(blank=True, choices=[('insufficient', 'Недостаточно'), ('threshold', 'Порог'), ('average', 'Средний балл'), ('high', 'Высокий')], max_length=20, null=True, verbose_name='Уровень (цвет)'),
        ),
        migrations.AlterField(
            model_name='previewtype',
            name='preview_type_text',
            field=models.CharField(max_length=200),
        ),
    ]
