# Generated by Django 5.2.11 on 2026-03-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0017_add_mark_score_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='score_level',
        ),
        migrations.AddField(
            model_name='markcomment',
            name='score_level',
            field=models.CharField(blank=True, choices=[('insufficient', 'Недостаточно'), ('threshold', 'Порог'), ('average', 'Средний балл'), ('high', 'Высокий')], max_length=20, null=True, verbose_name='Уровень (цвет)'),
        ),
    ]
