# Generated by Django 5.2.11 on 2026-03-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0018_move_score_level_to_markcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markcomment',
            name='score_level',
        ),
    ]
