# Generated by Django 5.2.11 on 2026-03-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0019_remove_score_level_from_markcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='markcomment',
            name='mark_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Недостаточно'), (2, 'Порог'), (3, 'Средний балл'), (4, 'Высокий')], default=0),
        ),
    ]
