# Generated by Django 5.2.11 on 2026-03-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0021_add_report_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportRecipient',
        ),
    ]
