# Generated by Django 5.2.11 on 2026-03-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0022_remove_report_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='Generator.tasklist')),
            ],
            options={
                'verbose_name': 'Подтемы',
                'ordering': ['order', 'title'],
                'unique_together': {('task_list', 'title')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Generator.subtopic'),
        ),
    ]
