# Generated by Django 5.2.11 on 2026-03-15 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0023_subtopic_task_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст обновления')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('show', models.BooleanField(choices=[(True, 'Показывать'), (False, 'Скрыть')], default=True, help_text='Показывать это обновление пользователям', verbose_name='Статус показа')),
            ],
            options={
                'verbose_name': 'Обновление',
                'verbose_name_plural': 'Обновления',
                'ordering': ['-date'],
            },
        ),
    ]
