# Generated by Django 5.2.11 on 2026-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0025_update_model_title_description_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='subdivision',
            field=models.CharField(blank=True, choices=[('ALG', 'Алгебра'), ('GEO', 'Геометрия')], help_text='Только для математики: Алгебра / Геометрия', max_length=20, verbose_name='Подраздел'),
        ),
    ]
