# Generated by Django 5.2.11 on 2026-03-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0026_add_tasklist_subdivision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Баллы и оценки'},
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_groups', to='Generator.subtopic'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='subdivision',
            field=models.CharField(blank=True, choices=[('alg', 'Алгебра'), ('geom', 'Геометрия')], help_text='Только для математики: Алгебра / Геометрия', max_length=20, verbose_name='Подраздел'),
        ),
    ]
