# Generated by Django 5.2.11 on 2026-03-22 06:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0027_add_subtopic_to_taskgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_text', django_ckeditor_5.fields.CKEditor5Field()),
                ('criteria_score', models.IntegerField(default=0)),
                ('task_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.tasklist')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
    ]
