# Generated by Django 5.2.11 on 2026-05-03 13:58

import django.db.models.deletion
from django.db import migrations, models


def seed_difficulty_tags(apps, schema_editor):
    TagType = apps.get_model("Generator", "TagType")
    TagOption = apps.get_model("Generator", "TagOption")
    tt, _ = TagType.objects.get_or_create(
        slug="difficulty",
        defaults={
            "name": "Сложность",
            "description": "Уровень подготовки / сложность материала",
            "order": 0,
        },
    )
    rows = [
        ("novice", "🌱", "Новичок", "green", 1),
        ("confident", "⚡", "Уверенный", "yellow", 2),
        ("expert", "🔥", "Эксперт", "red", 3),
    ]
    for slug, emoji, title, style, order in rows:
        TagOption.objects.update_or_create(
            tag_type=tt,
            slug=slug,
            defaults={
                "emoji": emoji,
                "title": title,
                "badge_style": style,
                "order": order,
                "is_active": True,
            },
        )


def unseed_difficulty_tags(apps, schema_editor):
    TagType = apps.get_model("Generator", "TagType")
    TagType.objects.filter(slug="difficulty").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0041_lesson_result_and_answer_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True, verbose_name="Код")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Тип тегов",
                "verbose_name_plural": "Типы тегов",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TagOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(verbose_name="Код")),
                ("emoji", models.CharField(blank=True, default="", max_length=16, verbose_name="Эмодзи")),
                ("title", models.CharField(max_length=120, verbose_name="Подпись")),
                (
                    "badge_style",
                    models.CharField(
                        choices=[
                            ("green", "Зелёный"),
                            ("yellow", "Жёлтый"),
                            ("red", "Красный"),
                            ("neutral", "Нейтральный"),
                            ("blue", "Синий"),
                        ],
                        default="neutral",
                        max_length=20,
                        verbose_name="Стиль бейджа",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "tag_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="Generator.tagtype",
                        verbose_name="Тип тега",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег (справочник)",
                "verbose_name_plural": "Теги (справочник)",
                "ordering": ("tag_type", "order", "id"),
                "constraints": [
                    models.UniqueConstraint(fields=("tag_type", "slug"), name="uniq_generator_tagoption_type_slug")
                ],
            },
        ),
        migrations.RunPython(seed_difficulty_tags, unseed_difficulty_tags),
    ]
