# Generated by Django 5.2.11 on 2026-05-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0042_tag_type_and_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='button_url',
            field=models.CharField(blank=True, help_text='Полный URL или путь на сайте, например /oge', max_length=500, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
