# Generated by Django 5.2.11 on 2026-05-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0046_task_vpr_flags_boolean_nonnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='vpr_advanced',
            field=models.BooleanField(db_index=True, default=False, help_text='Углублённый уровень (ВПР).', verbose_name='Углублённый'),
        ),
        migrations.AlterField(
            model_name='task',
            name='vpr_basic',
            field=models.BooleanField(db_index=True, default=False, help_text='Базовый уровень (ВПР).', verbose_name='Базовый'),
        ),
        migrations.AlterField(
            model_name='task',
            name='vpr_class',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Класс для ВПР (например 7, 8, 10). Только для заданий уровня ВПР.', null=True, verbose_name='Класс'),
        ),
    ]
