# Generated by Django 5.2.11 on 2026-05-05 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0054_fill_empty_quick_level_oge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.ForeignKey(
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Generator.tasklist",
                verbose_name="Задача",
            ),
        ),
    ]
