# Generated by Django 5.2.11 on 2026-06-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0059_oge_inf13_task_template_paragraphs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pedagogicalrecommendation',
            new_name='Generator_p_subject_a003c8_idx',
            old_name='Generator_p_subject_2c69ec_idx',
        ),
        migrations.RenameIndex(
            model_name='pedagogicalrecommendation',
            new_name='Generator_p_topic_10284a_idx',
            old_name='Generator_p_topic_ac5b48_idx',
        ),
        migrations.RenameIndex(
            model_name='pedagogicalrecommendation',
            new_name='Generator_p_is_acti_b56744_idx',
            old_name='Generator_p_is_acti_1e5f4c_idx',
        ),
        migrations.RenameIndex(
            model_name='reportconclusiontemplate',
            new_name='Generator_r_result__cad89d_idx',
            old_name='Generator_r_result__6974bc_idx',
        ),
        migrations.RenameIndex(
            model_name='reportconclusiontemplate',
            new_name='Generator_r_subject_bedea6_idx',
            old_name='Generator_r_subject_4c8d2d_idx',
        ),
        migrations.RenameIndex(
            model_name='reportnextsteptemplate',
            new_name='Generator_r_conditi_d4adc0_idx',
            old_name='Generator_r_conditi_0b9ed8_idx',
        ),
        migrations.RenameIndex(
            model_name='reportnextsteptemplate',
            new_name='Generator_r_subject_a9aedf_idx',
            old_name='Generator_r_subject_ede847_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='tag_options',
            field=models.ManyToManyField(blank=True, help_text='Теги задания из справочника (сложность и др.). Выбираются прямо здесь.', related_name='tasks', to='Generator.tagoption', verbose_name='Теги'),
        ),
    ]
