# Generated by Django 5.2.11 on 2026-06-07 20:52

import Generator.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0060_rename_generator_p_subject_2c69ec_idx_generator_p_subject_a003c8_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("file", models.FileField(upload_to=Generator.models.lesson_file_resource_upload_to)),
                ("file_type", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("allow_download", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(db_index=True, max_length=255, unique=True)),
                ("subject", models.CharField(db_index=True, max_length=120)),
                ("grade", models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ("level", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                (
                    "exam_type",
                    models.CharField(
                        blank=True,
                        choices=[("", "Без экзамена"), ("oge", "ОГЭ"), ("ege", "ЕГЭ")],
                        db_index=True,
                        default="",
                        max_length=10,
                    ),
                ),
                ("task_number", models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ("topic", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("subtopic", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("short_description", models.TextField(blank=True, default="")),
                ("teacher_goal", models.TextField(blank=True, default="")),
                ("student_result", models.TextField(blank=True, default="")),
                ("duration_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("beginner", "Beginner"), ("medium", "Medium"), ("advanced", "Advanced")],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликован"), ("archived", "Архив")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("free", "Бесплатный"), ("paid", "Платный"), ("private", "Закрытый")],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to=Generator.models.lesson_cover_upload_to),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(fields=["status", "access_level"], name="lesson_status_access_idx"),
                    models.Index(fields=["subject", "grade"], name="lesson_subject_grade_idx"),
                    models.Index(fields=["level", "exam_type"], name="lesson_level_exam_idx"),
                    models.Index(fields=["topic", "subtopic"], name="lesson_topic_subtopic_idx"),
                    models.Index(fields=["difficulty"], name="lesson_difficulty_idx"),
                    models.Index(fields=["task_number"], name="lesson_task_number_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "original_file",
                    models.FileField(
                        storage=Generator.models.PrivateMediaStorage(),
                        upload_to=Generator.models.presentation_original_upload_to,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=Generator.models.presentation_public_pdf_upload_to,
                    ),
                ),
                ("slides_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="LessonBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("presentation", "Презентация"),
                            ("tasks", "Задачи"),
                            ("quiz", "Квиз"),
                            ("video", "Видео"),
                            ("pdf", "PDF"),
                            ("file", "Файл"),
                            ("homework", "Домашнее задание"),
                            ("teacher_note", "Заметка учителю"),
                            ("divider", "Разделитель"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("is_visible_to_student", models.BooleanField(db_index=True, default=True)),
                ("is_visible_to_teacher", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="Generator.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "indexes": [
                    models.Index(fields=["lesson", "order"], name="lessonblock_lesson_order_idx"),
                    models.Index(fields=["block_type"], name="lessonblock_type_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("lesson", "order"), name="uniq_lesson_block_order"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PresentationSlide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(upload_to=Generator.models.presentation_slide_upload_to),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="Generator.presentation",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "indexes": [
                    models.Index(fields=["presentation", "order"], name="presentation_slide_order_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("presentation", "order"), name="uniq_presentation_slide_order"),
                ],
            },
        ),
    ]
