# Generated by Django 5.2.11 on 2026-06-07 21:26

from django.db import migrations
from django.db.models import Count


SAMPLE_LESSON_SLUG = "demo-informatics-spreadsheets-oge-10"


def recalc_presentations_slides_count(apps, schema_editor):
    Presentation = apps.get_model("Generator", "Presentation")
    PresentationSlide = apps.get_model("Generator", "PresentationSlide")

    Presentation.objects.all().update(slides_count=0)
    counts = (
        PresentationSlide.objects.values("presentation_id")
        .annotate(total=Count("id"))
    )
    for row in counts:
        presentation_id = row.get("presentation_id")
        total = int(row.get("total") or 0)
        if presentation_id:
            Presentation.objects.filter(id=presentation_id).update(slides_count=total)


def seed_ready_lesson_demo(apps, schema_editor):
    Lesson = apps.get_model("Generator", "Lesson")
    LessonBlock = apps.get_model("Generator", "LessonBlock")
    Task = apps.get_model("Generator", "Task")

    lesson, created = Lesson.objects.get_or_create(
        slug=SAMPLE_LESSON_SLUG,
        defaults={
            "title": "Электронные таблицы: анализ данных (демо)",
            "subject": "Информатика",
            "grade": 9,
            "level": "ОГЭ",
            "exam_type": "oge",
            "task_number": 10,
            "topic": "Электронные таблицы",
            "subtopic": "Формулы, фильтрация и анализ",
            "short_description": "Готовый демо-урок: теория, практика, домашнее задание и заметки для учителя.",
            "teacher_goal": "Научить ученика уверенно работать с базовыми формулами и фильтрами в таблицах.",
            "student_result": "Ученик умеет читать условие, строить формулы и проверять результат в табличных заданиях.",
            "duration_minutes": 45,
            "difficulty": "medium",
            "status": "published",
            "access_level": "free",
        },
    )
    if not created:
        return

    task_ids = list(
        Task.objects.filter(is_active=True).order_by("id").values_list("id", flat=True)[:5]
    )
    practice_ids = task_ids[:3]
    homework_ids = task_ids[3:5]

    LessonBlock.objects.bulk_create(
        [
            LessonBlock(
                lesson=lesson,
                block_type="text",
                title="Вводная часть",
                order=10,
                content={
                    "html": "<p>Сегодня разбираем электронные таблицы: формулы, фильтрацию и типовые ошибки в вычислениях.</p>"
                },
                is_visible_to_student=True,
                is_visible_to_teacher=True,
            ),
            LessonBlock(
                lesson=lesson,
                block_type="presentation",
                title="Презентация урока",
                order=20,
                content={"view_mode": "slides"},
                is_visible_to_student=True,
                is_visible_to_teacher=True,
            ),
            LessonBlock(
                lesson=lesson,
                block_type="tasks",
                title="Практика на уроке",
                order=30,
                content={
                    "task_ids": practice_ids,
                    "show_answers": False,
                    "mode": "practice",
                },
                is_visible_to_student=True,
                is_visible_to_teacher=True,
            ),
            LessonBlock(
                lesson=lesson,
                block_type="homework",
                title="Домашнее задание",
                order=40,
                content={
                    "task_ids": homework_ids,
                    "comment": "Решить до следующего занятия, обратить внимание на точность формул.",
                },
                is_visible_to_student=True,
                is_visible_to_teacher=True,
            ),
            LessonBlock(
                lesson=lesson,
                block_type="teacher_note",
                title="Методическая заметка",
                order=50,
                content={
                    "html": "<p>Попросите учеников проговорить логику формулы перед вводом в ячейку: это снижает число механических ошибок.</p>"
                },
                is_visible_to_student=False,
                is_visible_to_teacher=True,
            ),
        ]
    )


def unseed_ready_lesson_demo(apps, schema_editor):
    Lesson = apps.get_model("Generator", "Lesson")
    Lesson.objects.filter(slug=SAMPLE_LESSON_SLUG).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0061_lessons_architecture"),
    ]

    operations = [
        migrations.RunPython(recalc_presentations_slides_count, migrations.RunPython.noop),
        migrations.RunPython(seed_ready_lesson_demo, unseed_ready_lesson_demo),
    ]
