# Generated by Django 5.2.11 on 2026-06-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0062_seed_ready_lessons_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('presentation', 'Презентация'), ('html', 'HTML')], db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible_to_student', models.BooleanField(db_index=True, default=True)),
                ('is_visible_to_teacher', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Generator.lesson')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='tag_options',
        ),
        migrations.CreateModel(
            name='HtmlStep',
            fields=[
                ('lessonstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Generator.lessonstep')),
                ('content', models.TextField(blank=True, default='')),
            ],
            bases=('Generator.lessonstep',),
        ),
        migrations.CreateModel(
            name='PresentationStep',
            fields=[
                ('lessonstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Generator.lessonstep')),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_steps', to='Generator.presentation')),
            ],
            bases=('Generator.lessonstep',),
        ),
        migrations.AddIndex(
            model_name='lessonstep',
            index=models.Index(fields=['lesson', 'order'], name='lessonstep_lesson_order_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonstep',
            index=models.Index(fields=['step_type'], name='lessonstep_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonstep',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_lesson_step_order'),
        ),
    ]
