# Generated by Django 5.2.11 on 2026-06-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0063_lessonstep_remove_task_tag_options_htmlstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericStep',
            fields=[
                ('lessonstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Generator.lessonstep')),
                ('content', models.JSONField(blank=True, default=dict)),
            ],
            bases=('Generator.lessonstep',),
        ),
        migrations.AlterField(
            model_name='lessonstep',
            name='step_type',
            field=models.CharField(choices=[('text', 'Текст'), ('presentation', 'Презентация'), ('tasks', 'Задачи'), ('quiz', 'Квиз'), ('video', 'Видео'), ('pdf', 'PDF'), ('file', 'Файл'), ('homework', 'Домашнее задание'), ('teacher_note', 'Заметка учителю'), ('divider', 'Разделитель'), ('html', 'HTML')], db_index=True, max_length=30),
        ),
    ]
