# Generated by Django 5.2.11 on 2026-06-08 16:53

from django.db import migrations

def migrate_blocks_to_steps(apps, schema_editor):
    LessonBlock = apps.get_model('Generator', 'LessonBlock')
    LessonStep = apps.get_model('Generator', 'LessonStep')
    PresentationStep = apps.get_model('Generator', 'PresentationStep')
    HtmlStep = apps.get_model('Generator', 'HtmlStep')
    GenericStep = apps.get_model('Generator', 'GenericStep')
    Presentation = apps.get_model('Generator', 'Presentation')

    for block in LessonBlock.objects.all():
        step_type = block.block_type
        
        # Base step fields
        step_kwargs = {
            'lesson': block.lesson,
            'step_type': step_type,
            'title': block.title,
            'order': block.order,
            'is_visible_to_student': block.is_visible_to_student,
            'is_visible_to_teacher': block.is_visible_to_teacher,
            'created_at': block.created_at,
            'updated_at': block.updated_at,
        }

        if step_type == 'presentation':
            presentation_id = block.content.get('presentation_id') if isinstance(block.content, dict) else None
            presentation = None
            if presentation_id:
                try:
                    presentation = Presentation.objects.get(id=int(presentation_id))
                except (ValueError, TypeError, Presentation.DoesNotExist):
                    pass
            
            PresentationStep.objects.create(
                presentation=presentation,
                **step_kwargs
            )
        elif step_type == 'html':
            HtmlStep.objects.create(
                content=block.content if isinstance(block.content, str) else str(block.content),
                **step_kwargs
            )
        else:
            GenericStep.objects.create(
                content=block.content if isinstance(block.content, dict) else {},
                **step_kwargs
            )

def reverse_migrate_steps_to_blocks(apps, schema_editor):
    LessonBlock = apps.get_model('Generator', 'LessonBlock')
    LessonStep = apps.get_model('Generator', 'LessonStep')
    
    for step in LessonStep.objects.all():
        content = {}
        if hasattr(step, 'presentationstep'):
            p_step = step.presentationstep
            if p_step.presentation:
                content = {'presentation_id': p_step.presentation.id}
        elif hasattr(step, 'htmlstep'):
            content = step.htmlstep.content
        elif hasattr(step, 'genericstep'):
            content = step.genericstep.content

        LessonBlock.objects.create(
            lesson=step.lesson,
            block_type=step.step_type,
            title=step.title,
            order=step.order,
            content=content,
            is_visible_to_student=step.is_visible_to_student,
            is_visible_to_teacher=step.is_visible_to_teacher,
            created_at=step.created_at,
            updated_at=step.updated_at,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0064_genericstep_alter_lessonstep_step_type'),
    ]

    operations = [
        migrations.RunPython(migrate_blocks_to_steps, reverse_migrate_steps_to_blocks),
    ]
