# Generated by Django 5.2.11 on 2026-06-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0065_migrate_lesson_blocks_to_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonBlock',
        ),
    ]
