# Generated by Django 5.2.11 on 2026-06-08 19:17

import Generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0066_delete_lessonblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileResource',
        ),
        migrations.RemoveField(
            model_name='genericstep',
            name='lessonstep_ptr',
        ),
        migrations.RemoveField(
            model_name='htmlstep',
            name='lessonstep_ptr',
        ),
        migrations.DeleteModel(
            name='LessonRoom',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='presentationstep',
            name='lessonstep_ptr',
        ),
        migrations.DeleteModel(
            name='LessonStudentResult',
        ),
        migrations.DeleteModel(
            name='LessonStudentsAnswer',
        ),
        migrations.RemoveField(
            model_name='presentationstep',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='presentationslide',
            name='presentation',
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Generator.models.lesson_file_upload_to),
        ),
        migrations.DeleteModel(
            name='GenericStep',
        ),
        migrations.DeleteModel(
            name='HtmlStep',
        ),
        migrations.DeleteModel(
            name='LessonStep',
        ),
        migrations.DeleteModel(
            name='PresentationStep',
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
        migrations.DeleteModel(
            name='PresentationSlide',
        ),
    ]
