# Generated by Django 5.2.11 on 2026-06-09 14:59

import Generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0067_delete_fileresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='archive',
            field=models.FileField(blank=True, help_text='ZIP, RAR или 7Z с материалами урока', null=True, upload_to=Generator.models.lesson_archive_upload_to, verbose_name='Архив'),
        ),
    ]
