# Generated by Django 5.2.11 on 2026-06-10 06:28

import Generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0068_lesson_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='card_background_color',
            field=models.CharField(blank=True, default='', help_text='Например, #2B52F5', max_length=7, verbose_name='Фон карточки (HEX цвет)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='card_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=Generator.models.lesson_cover_upload_to, verbose_name='Фон карточки (картинка)'),
        ),
    ]
