# Generated by Django 5.2.11 on 2026-07-08 13:50

import Generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0069_lesson_card_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="background_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например, #311B41. Используется, если не задано изображение.",
                max_length=7,
                verbose_name="Фон предмета (HEX цвет)",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Generator.models.subject_background_upload_to,
                verbose_name="Фон предмета (картинка)",
                help_text="Декоративный фон для карточки предмета и hero-блока генератора вариантов.",
            ),
        ),
    ]
