# Generated by Django 5.2.11 on 2026-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0070_subject_background_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag_options',
            field=models.ManyToManyField(blank=True, help_text='Теги задания из справочника (сложность и др.).', related_name='tasks', to='Generator.tagoption', verbose_name='Теги'),
        ),
    ]
