# Generated by Django 5.2.11 on 2026-07-26 09:41

import Generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0071_restore_task_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Краткое описание')),
                ('tag', models.CharField(blank=True, default='Интерактив', help_text='Например: Интерактив, Факт', max_length=80, verbose_name='Метка')),
                ('accent_color', models.CharField(blank=True, default='#1F3A8A', help_text='HEX, если нет обложки. Например #1F3A8A', max_length=7, verbose_name='Цвет карточки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=Generator.models.interesting_cover_upload_to, verbose_name='Обложка')),
                ('file', models.FileField(blank=True, help_text='Одиночный HTML или другой файл интерактива', null=True, upload_to=Generator.models.interesting_file_upload_to, verbose_name='Файл')),
                ('archive', models.FileField(blank=True, help_text='ZIP с index.html и ресурсами интерактива', null=True, upload_to=Generator.models.interesting_archive_upload_to, verbose_name='Архив')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Интересное',
                'verbose_name_plural': 'Интересное',
                'ordering': ('sort_order', '-updated_at', 'id'),
                'indexes': [models.Index(fields=['status', 'sort_order'], name='interesting_status_order_idx')],
            },
        ),
    ]
