# Generated by Django 5.2.11 on 2026-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0072_interesting_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='new_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='access_level',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('teacher', 'Учитель'), ('professional', 'Профи'), ('premium', 'Премиум'), ('corporate', 'Корпоративный'), ('paid', 'Платный (legacy)'), ('private', 'Закрытый (legacy)')], db_index=True, default='free', max_length=20),
        ),
    ]
