# Generated by Django 5.2.11 on 2026-08-04 10:16

import Generator.seasonal_theme_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0073_tariffs_subscriptions_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, help_text='Черновики и отключённые темы не участвуют в автовыборе.', verbose_name='Разрешена')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Чем больше число, тем выше приоритет при пересечении периодов.', verbose_name='Приоритет')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало показа')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание показа')),
                ('timezone', models.CharField(default='Europe/Moscow', help_text='Используется для интерпретации дат показа.', max_length=64, verbose_name='Часовой пояс')),
                ('allow_user_disable', models.BooleanField(default=True, verbose_name='Пользователь может отключить')),
                ('allow_manual_selection', models.BooleanField(default=True, verbose_name='Можно выбрать вручную')),
                ('is_default_seasonal_theme', models.BooleanField(default=True, help_text='Участвует в автоматическом выборе по датам.', verbose_name='Основная тема периода')),
                ('background_color', models.CharField(blank=True, default='', max_length=32, verbose_name='Цвет фона')),
                ('background_pattern', models.ImageField(blank=True, null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Паттерн фона')),
                ('background_pattern_mobile', models.ImageField(blank=True, null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Паттерн фона (mobile)')),
                ('background_repeat', models.CharField(choices=[('repeat', 'repeat'), ('repeat-x', 'repeat-x'), ('repeat-y', 'repeat-y'), ('no-repeat', 'no-repeat')], default='repeat', max_length=16, verbose_name='Повтор паттерна')),
                ('background_size', models.CharField(blank=True, default='240px', max_length=64, verbose_name='Размер паттерна')),
                ('background_position', models.CharField(blank=True, default='center', max_length=64, verbose_name='Позиция паттерна')),
                ('background_opacity', models.FloatField(default=0.18, verbose_name='Прозрачность паттерна')),
                ('background_overlay_color', models.CharField(blank=True, default='', max_length=32, verbose_name='Цветовой слой поверх фона')),
                ('background_overlay_opacity', models.FloatField(default=0.0, verbose_name='Прозрачность цветового слоя')),
                ('disable_background_on_low_end', models.BooleanField(default=True, verbose_name='Отключать фон на слабых устройствах')),
                ('surfaces', models.JSONField(blank=True, default=dict, verbose_name='Оформление поверхностей')),
                ('animation_type', models.CharField(choices=[('none', 'Без анимации'), ('fade_in', 'Лёгкое плавное появление'), ('sway', 'Медленное покачивание'), ('float', 'Мягкое парение'), ('twinkle', 'Редкое мерцание'), ('pattern_drift', 'Медленное движение фонового паттерна'), ('snow', 'Падающий снег'), ('leaves', 'Падающие листья'), ('confetti', 'Конфетти при первом открытии'), ('floating_decor', 'Плавающие декоративные элементы')], default='none', max_length=32, verbose_name='Тип анимации')),
                ('animation_intensity', models.CharField(choices=[('off', 'Выкл'), ('minimal', 'Минимальная'), ('normal', 'Обычная'), ('festive', 'Праздничная')], default='minimal', max_length=16, verbose_name='Интенсивность анимации')),
                ('animation_max_elements', models.PositiveSmallIntegerField(default=20, verbose_name='Макс. элементов анимации')),
                ('animation_fps_limit', models.PositiveSmallIntegerField(default=24, verbose_name='Ограничение FPS (сложные эффекты)')),
                ('include_routes', models.JSONField(blank=True, default=list, help_text='Список префиксов/путей, например ["/cabinet", "/"]. Пусто = везде, кроме exclude.', verbose_name='Показывать только на маршрутах')),
                ('exclude_routes', models.JSONField(blank=True, default=list, help_text='Например ["/cabinet/boards", "/cabinet/meetings", "/lessons"].', verbose_name='Не показывать на маршрутах')),
                ('force_active_for_testing', models.BooleanField(default=False, help_text='Игнорирует даты; тема становится кандидатом на автовыбор для всех.', verbose_name='Принудительно активировать (тест)')),
                ('admin_only', models.BooleanField(default=False, help_text='Тема видна обычным пользователям только через предпросмотр.', verbose_name='Только для администраторов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сезонная тема',
                'verbose_name_plural': 'Сезонные темы',
                'ordering': ['-priority', '-start_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalThemeDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('image', models.FileField(blank=True, help_text='Разрешены PNG, JPEG, WebP, GIF, AVIF; SVG — только проверенные администратором файлы.', null=True, upload_to=Generator.seasonal_theme_models.seasonal_decoration_upload_to, verbose_name='Изображение / SVG')),
                ('zone', models.CharField(choices=[('page_background', 'Общий фон страницы'), ('top_bar', 'Верхняя панель'), ('sidebar', 'Боковое меню'), ('task_cards', 'Карточки задач'), ('lesson_cards', 'Карточки уроков'), ('dashboard', 'Дашборд'), ('catalog', 'Каталог'), ('profile', 'Профиль'), ('login', 'Экран входа'), ('custom_routes', 'Конкретные маршруты')], default='page_background', max_length=32, verbose_name='Зона отображения')),
                ('custom_routes', models.JSONField(blank=True, default=list, verbose_name='Маршруты (для зоны custom_routes)')),
                ('position', models.CharField(choices=[('top-left', 'Верхний левый'), ('top-right', 'Верхний правый'), ('bottom-left', 'Нижний левый'), ('bottom-right', 'Нижний правый'), ('center', 'Центр'), ('custom', 'Свои координаты')], default='top-right', max_length=32, verbose_name='Позиция')),
                ('offset_x', models.CharField(blank=True, default='0', max_length=32, verbose_name='Отступ X')),
                ('offset_y', models.CharField(blank=True, default='0', max_length=32, verbose_name='Отступ Y')),
                ('width', models.CharField(blank=True, default='80px', max_length=32, verbose_name='Ширина')),
                ('height', models.CharField(blank=True, default='auto', max_length=32, verbose_name='Высота')),
                ('opacity', models.FloatField(default=0.85, verbose_name='Прозрачность')),
                ('z_index', models.SmallIntegerField(default=1, verbose_name='z-index')),
                ('show_desktop', models.BooleanField(default=True, verbose_name='Показывать на компьютере')),
                ('show_tablet', models.BooleanField(default=True, verbose_name='Показывать на планшете')),
                ('show_mobile', models.BooleanField(default=False, verbose_name='Показывать на телефоне')),
                ('click_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка при нажатии')),
                ('animation_type', models.CharField(choices=[('none', 'Без анимации'), ('fade_in', 'Появление'), ('sway', 'Покачивание'), ('float', 'Парение'), ('twinkle', 'Мерцание')], default='none', max_length=32, verbose_name='Анимация')),
                ('animation_speed', models.FloatField(default=6.0, verbose_name='Скорость анимации (сек)')),
                ('animation_delay', models.FloatField(default=0.0, verbose_name='Задержка запуска (сек)')),
                ('intensity', models.CharField(choices=[('off', 'Выкл'), ('minimal', 'Минимальная'), ('normal', 'Обычная'), ('festive', 'Праздничная')], default='minimal', max_length=16, verbose_name='Интенсивность')),
                ('max_concurrent', models.PositiveSmallIntegerField(default=1, verbose_name='Макс. одновременно отображаемых')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='Generator.seasonaltheme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Декор сезонной темы',
                'verbose_name_plural': 'Декор сезонных тем',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
