# Generated by Django 5.2.11 on 2026-08-04 10:26

import Generator.seasonal_theme_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0075_seasonal_theme_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonaltheme',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Например #4D8FC9', max_length=32, verbose_name='Акцентный цвет'),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='button_icon',
            field=models.ImageField(blank=True, help_text='Показывается на плавающей кнопке в левом нижнем углу. Без файла — кнопка со стандартной иконкой.', null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Иконка кнопки «Оформление»'),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='card_border_color',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Цвет границы карточек'),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='card_pattern',
            field=models.ImageField(blank=True, help_text='Лёгкий паттерн поверх карточек задач/уроков.', null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Паттерн карточек'),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='card_pattern_opacity',
            field=models.FloatField(default=0.12, verbose_name='Прозрачность паттерна карточек'),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='corner_image',
            field=models.ImageField(blank=True, help_text='Необязательная картинка в углу экрана (не путать с кнопкой оформления).', null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Декор в углу страницы'),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='header_decor',
            field=models.ImageField(blank=True, null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Декор верхней панели'),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='menu_background',
            field=models.ImageField(blank=True, help_text='Картинка/паттерн для бокового меню кабинета.', null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Фон бокового меню'),
        ),
    ]
