# Generated by Django 5.2.11 on 2026-08-04 10:30

import Generator.seasonal_theme_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0076_seasonal_theme_simple_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonaltheme',
            name='button_emoji',
            field=models.CharField(blank=True, default='✦', help_text='Если картинка не загружена — на кнопке будет этот смайлик (вставьте с клавиатуры, напр. 🎄 🎃 🌸).', max_length=16, verbose_name='Смайлик кнопки «Оформление»'),
        ),
        migrations.AlterField(
            model_name='seasonaltheme',
            name='button_icon',
            field=models.ImageField(blank=True, help_text='Картинка на плавающей кнопке в левом нижнем углу. Если пусто — используется смайлик ниже.', null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Иконка кнопки «Оформление»'),
        ),
    ]
