# Generated by Django 5.2.11 on 2026-08-04 13:23

import Generator.seasonal_theme_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0077_seasonal_theme_button_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonaltheme',
            name='animation_image',
            field=models.ImageField(blank=True, help_text='PNG/WebP с прозрачностью: листочек, снежинка, капелька мёда и т.п. Именно эта картинка будет сыпаться по экрану. Без файла — встроенный рисунок (снег/листья/конфетти).', null=True, upload_to=Generator.seasonal_theme_models.seasonal_theme_upload_to, verbose_name='Картинка элемента анимации'),
        ),
        migrations.AlterField(
            model_name='seasonaltheme',
            name='force_active_for_testing',
            field=models.BooleanField(default=False, help_text='Игнорирует даты и флаг «Основная тема периода». Тема должна быть не черновиком и с «Разрешена» — тогда она кандидат на автовыбор.', verbose_name='Принудительно активировать (тест)'),
        ),
    ]
