# Generated by Django 5.2.11 on 2026-08-05 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0082_seasonal_theme_hero_history_image'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interestingitem',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='CatalogContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_content_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк материала каталога',
                'verbose_name_plural': 'Лайки материалов каталога',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='catalog_like_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_catalog_content_like')],
            },
        ),
        migrations.CreateModel(
            name='CatalogContentViewDedup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('visitor_key', models.CharField(blank=True, db_index=True, default='', help_text='Хеш cookie посетителя; IP не храним', max_length=64)),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_content_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр материала каталога',
                'verbose_name_plural': 'Просмотры материалов каталога',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'user', 'viewed_at'], name='catalog_view_user_idx'), models.Index(fields=['content_type', 'object_id', 'visitor_key', 'viewed_at'], name='catalog_view_visitor_idx')],
            },
        ),
    ]
