# Generated by Django 5.2.11 on 2026-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0084_criteria_axis_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="interestingitem",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("free", "Бесплатный (Старт)"),
                    ("teacher", "Учитель"),
                    ("professional", "Профи"),
                    ("premium", "Премиум"),
                    ("corporate", "Корпоративный"),
                ],
                db_index=True,
                default="free",
                max_length=20,
                verbose_name="Доступно с тарифа",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("free", "Бесплатный (Старт)"),
                    ("teacher", "Учитель"),
                    ("professional", "Профи"),
                    ("premium", "Премиум"),
                    ("corporate", "Корпоративный"),
                    ("paid", "Платный (legacy)"),
                    ("private", "Закрытый (legacy)"),
                ],
                db_index=True,
                default="free",
                help_text="Минимальный тариф, с которого материал доступен",
                max_length=20,
                verbose_name="Доступно с тарифа",
            ),
        ),
        migrations.AddIndex(
            model_name="interestingitem",
            index=models.Index(
                fields=["status", "access_level"],
                name="interesting_status_access_idx",
            ),
        ),
    ]
