# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0090_seed_ege_chem_tasklists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
