# Generated by Django 5.2.11 on 2026-09-06 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0092_seasonal_theme_meeting_header_decor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTaskBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_code', models.CharField(db_index=True, help_text='Короткий уникальный код, например K7M4P. Не меняется после создания.', max_length=8, unique=True, verbose_name='Код банка')),
                ('next_task_number', models.PositiveIntegerField(default=1, verbose_name='Следующий номер задачи')),
                ('next_variant_number', models.PositiveIntegerField(default=1, verbose_name='Следующий номер варианта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Банк задач учителя',
                'verbose_name_plural': 'Банки задач учителей',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='local_number',
            field=models.PositiveIntegerField(blank=True, help_text='Последовательный номер внутри банка конкретного учителя. Не переиспользуется.', null=True, verbose_name='Номер в банке учителя'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_bank_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец (учитель)'),
        ),
        migrations.AddField(
            model_name='task',
            name='scope',
            field=models.CharField(choices=[('global', 'Общий банк'), ('teacher', 'Банк учителя')], db_index=True, default='global', help_text='global — общий банк; teacher — личный банк учителя. Расширяемо (school/shared).', max_length=16, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_task',
            field=models.ForeignKey(blank=True, help_text='Откуда скопирована задача (общий банк или дубликат).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_tasks', to='Generator.task', verbose_name='Исходная задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готово'), ('archived', 'Архив')], db_index=True, default='ready', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='variant',
            name='local_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер варианта в банке учителя'),
        ),
        migrations.AddField(
            model_name='variant',
            name='owner_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_variants', to=settings.AUTH_USER_MODEL, verbose_name='Владелец (учитель)'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scope', 'is_active'], name='task_scope_active_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner_teacher', 'status'], name='task_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner_teacher', 'local_number'], name='task_owner_local_num_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scope', 'owner_teacher', 'is_active'], name='task_scope_owner_act_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['owner_teacher', 'local_number'], name='variant_owner_local_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('local_number__isnull', True), ('owner_teacher__isnull', True), ('scope', 'global')), models.Q(('local_number__isnull', False), ('owner_teacher__isnull', False), ('scope', 'teacher')), _connector='OR'), name='task_scope_owner_local_number_consistent'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'teacher')), fields=('owner_teacher', 'local_number'), name='task_owner_local_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('local_number__isnull', False), ('owner_teacher__isnull', False)), fields=('owner_teacher', 'local_number'), name='variant_owner_local_number_uniq'),
        ),
        migrations.AddField(
            model_name='teachertaskbank',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_bank', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
