# Generated by Django 5.2.11 on 2026-09-24 08:03

import Generator.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0096_varianttheme_block_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, default='', verbose_name='Полное описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=Generator.models.lesson_cover_upload_to, verbose_name='Обложка')),
                ('subject', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Предмет')),
                ('grade', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Класс')),
                ('level', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Направление')),
                ('exam_type', models.CharField(blank=True, choices=[('', 'Без экзамена'), ('oge', 'ОГЭ'), ('ege', 'ЕГЭ')], db_index=True, default='', max_length=10, verbose_name='Экзамен')),
                ('author', models.CharField(blank=True, default='', max_length=255, verbose_name='Автор')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('hidden', 'Скрыт'), ('archived', 'Архив')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('access_mode', models.CharField(choices=[('free', 'Бесплатно'), ('subscription', 'По тарифу'), ('purchase', 'Отдельная покупка'), ('subscription_or_purchase', 'Тариф или покупка')], db_index=True, default='subscription', max_length=32, verbose_name='Режим доступа')),
                ('plan_slugs', models.JSONField(blank=True, default=list, help_text='Slug тарифов, с которых набор доступен. Более высокий тариф включает нижние.', verbose_name='Тарифы')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('purchase_valid_days', models.PositiveIntegerField(blank=True, help_text='Пусто — доступ после покупки бессрочный.', null=True, verbose_name='Срок покупки, дни')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_collections', to='Generator.lessoncollection', verbose_name='Следующий набор')),
            ],
            options={
                'verbose_name': 'Набор уроков',
                'verbose_name_plural': 'Наборы уроков',
                'ordering': ('-published_at', '-created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='primary_collection',
            field=models.ForeignKey(blank=True, help_text='Какой набор показывать, если урок открыт не со страницы набора.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_lessons', to='Generator.lessoncollection', verbose_name='Основной набор'),
        ),
        migrations.CreateModel(
            name='LessonCollectionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Generator.lessoncollection', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Раздел набора',
                'verbose_name_plural': 'Разделы набора',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LessonCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_demo', models.BooleanField(default=False, help_text='Этот урок можно открыть без покупки набора.', verbose_name='Демоурок')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Generator.lessoncollection', verbose_name='Набор')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='Generator.lesson', verbose_name='Урок')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Generator.lessoncollectionsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Урок в наборе',
                'verbose_name_plural': 'Уроки в наборе',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='lessoncollection',
            index=models.Index(fields=['status', 'subject'], name='lcol_status_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncollection',
            index=models.Index(fields=['status', 'grade'], name='lcol_status_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncollectionitem',
            index=models.Index(fields=['lesson', 'collection'], name='lcol_item_lesson_col_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncollectionitem',
            index=models.Index(fields=['collection', 'position'], name='lcol_item_col_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessoncollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'lesson'), name='lcol_item_collection_lesson_uniq'),
        ),
    ]
