# Generated by Django 5.2.11 on 2026-09-24 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0097_lesson_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncollectionitem',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Материал в наборе', 'verbose_name_plural': 'Материалы в наборе'},
        ),
        migrations.RemoveConstraint(
            model_name='lessoncollectionitem',
            name='lcol_item_collection_lesson_uniq',
        ),
        migrations.AddField(
            model_name='lessoncollectionitem',
            name='interesting_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='Generator.interestingitem', verbose_name='Тренажёр'),
        ),
        migrations.AlterField(
            model_name='lessoncollectionitem',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='Generator.lesson', verbose_name='Урок'),
        ),
        migrations.AddConstraint(
            model_name='lessoncollectionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('collection', 'lesson'), name='lcol_item_collection_lesson_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lessoncollectionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('interesting_item__isnull', False)), fields=('collection', 'interesting_item'), name='lcol_item_collection_trainer_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lessoncollectionitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interesting_item__isnull', True), ('lesson__isnull', False)), models.Q(('interesting_item__isnull', False), ('lesson__isnull', True)), _connector='OR'), name='lcol_item_one_target'),
        ),
    ]
