# Generated by Django 5.2.11 on 2026-10-04 04:56

import Generator.variant_theme_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0103_restore_lesson_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterField(
            model_name='lessoncollectionitem',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Этот материал можно открыть без покупки набора.', verbose_name='Демо'),
        ),
        migrations.AlterField(
            model_name='varianttheme',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: labels, decorations, animation, background. Можно задать animation=travel-route и background.type=gradient.', verbose_name='Конфигурация'),
        ),
        migrations.AlterField(
            model_name='varianttheme',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Картинка в каталоге тем. Выберите файл и нажмите «Сохранить».', null=True, upload_to=Generator.variant_theme_models.variant_theme_upload_to, verbose_name='Превью'),
        ),
    ]
