# Generated by Django 5.2.11 on 2026-09-23 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_kind', models.CharField(max_length=64, unique=True)),
                ('retain_days', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Срок хранения',
                'verbose_name_plural': 'Сроки хранения',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('support', 'Поддержка'), ('platform', 'От разработчика')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'permissions': [('support', 'Отвечать в поддержке и вести обращения'), ('broadcast', 'Запускать массовые рассылки'), ('manage', 'Администрировать сообщения')],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_role', models.CharField(choices=[('owner', 'Владелец'), ('staff', 'Сотрудник')], max_length=16)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivered_message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('retention_policy_kind', models.CharField(default='delivery_metadata', max_length=64)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_read_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'Пользователь'), ('staff', 'Сотрудник'), ('system', 'Система')], max_length=16)),
                ('message_type', models.CharField(choices=[('message', 'Сообщение'), ('internal_note', 'Внутренняя заметка'), ('system_event', 'Системное событие')], default='message', max_length=32)),
                ('purpose', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField(blank=True)),
                ('client_message_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_retention_until', models.DateTimeField(blank=True, null=True)),
                ('content_retention_kind', models.CharField(default='message_content', max_length=64)),
                ('metadata_retention_until', models.DateTimeField(blank=True, null=True)),
                ('metadata_retention_kind', models.CharField(default='message_metadata', max_length=64)),
                ('legal_hold', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast_key', models.CharField(blank=True, max_length=64)),
                ('reply_disabled', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_route', models.CharField(blank=True, max_length=300)),
                ('display_mode', models.CharField(blank=True, max_length=32)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=127)),
                ('size', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=300, unique=True)),
                ('scan_status', models.CharField(choices=[('unscanned', 'Не проверен антивирусом'), ('scanning', 'Проверяется'), ('clean', 'Проверен антивирусом'), ('rejected', 'Отклонён проверкой'), ('scan_failed', 'Проверка не выполнена')], default='unscanned', max_length=16)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('retention_policy_kind', models.CharField(default='attachments', max_length=64)),
                ('legal_hold', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_revisions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='messaging.message')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MessagingAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('retention_policy_kind', models.CharField(default='access_logs', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_access_logs', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='messaging.conversation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MessagingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('object_kind', models.CharField(max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('retention_policy_kind', models.CharField(default='audit_logs', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('technical', 'Техническая проблема'), ('billing', 'Оплата и тариф'), ('materials', 'Материалы и задания'), ('lesson', 'Проведение урока'), ('account', 'Аккаунт'), ('suggestion', 'Предложение'), ('other', 'Другое')], max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('waiting_user', 'Ждём ответа пользователя'), ('resolved', 'Решено')], default='new', max_length=32)),
                ('priority', models.CharField(choices=[('normal', 'Обычный'), ('important', 'Важный'), ('urgent', 'Срочный')], default='normal', max_length=16)),
                ('technical_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='messaging.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.supportticket'),
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email_marketing', 'Email'), ('inapp_marketing', 'Сообщения платформы')], max_length=32)),
                ('granted', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('consent_text_version', models.CharField(blank=True, max_length=64)),
                ('text_sha256', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('action', models.CharField(choices=[('granted', 'Выдано'), ('revoked', 'Отозвано')], max_length=16)),
                ('consent_text_version', models.CharField(max_length=64)),
                ('text_sha256', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_retention_until', models.DateTimeField(blank=True, null=True)),
                ('log_retention_kind', models.CharField(default='consent_logs', max_length=64)),
                ('evidence_retention_until', models.DateTimeField(blank=True, null=True)),
                ('evidence_retention_kind', models.CharField(default='consent_evidence', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentPromptState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_key', models.CharField(max_length=64)),
                ('shown_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('consent_text_version', models.CharField(max_length=64)),
                ('text_sha256', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_prompt_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'prompt_key'), name='messaging_prompt_user_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('subject_user', 'kind'), name='messaging_conversation_subject_kind'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='messaging_participant_conversation_user'),
        ),
        migrations.AddConstraint(
            model_name='conversationreadstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='messaging_read_state_conversation_user'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'assigned_to', 'updated_at'], name='messaging_s_status_392e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'id'], name='messaging_m_convers_f5b548_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_m_convers_7bc91b_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id', ''), _negated=True), fields=('conversation', 'client_message_id'), name='messaging_message_client_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='messaging_consent_user_channel'),
        ),
    ]
