# Generated by Django 5.2.11 on 2026-09-23 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='messaging_conversation_subject_kind',
        ),
        migrations.AddField(
            model_name='conversation',
            name='pair_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('support', 'Поддержка'), ('platform', 'От разработчика'), ('direct', 'Личный')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['support', 'platform'])), fields=('subject_user', 'kind'), name='messaging_conversation_official_subject_kind'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('pair_key', ''), _negated=True), fields=('pair_key',), name='messaging_conversation_direct_pair'),
        ),
    ]
