# Generated by Django 5.2.11 on 2026-10-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_teacher_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='channel',
            field=models.CharField(choices=[('email_marketing', 'Email'), ('inapp_marketing', 'Сообщения платформы'), ('personal_data', 'Обработка персональных данных')], max_length=32),
        ),
    ]
