# Generated by Django 5.2.11 on 2026-06-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='cabinet/avatars/', verbose_name='Аватар')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель'), ('parent', 'Родитель')], default='student', max_length=20, verbose_name='Роль')),
                ('account_status', models.CharField(default='active', max_length=32, verbose_name='Статус')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email подтверждён')),
                ('account_active', models.BooleanField(default=True, verbose_name='Аккаунт активен')),
                ('account_blocked', models.BooleanField(default=False, verbose_name='Аккаунт заблокирован')),
                ('date_blocked', models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
