# Generated by Django 5.2.11 on 2026-06-21 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yandex_account_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Yandex email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='yandex_calendar_layer_ids',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yandex calendar layer_ids'),
        ),
        migrations.AddField(
            model_name='profile',
            name='yandex_oauth_token',
            field=models.TextField(blank=True, verbose_name='Yandex OAuth token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='yandex_refresh_token',
            field=models.TextField(blank=True, verbose_name='Yandex refresh token'),
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('topic', models.CharField(blank=True, max_length=500, verbose_name='Тема')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание')),
                ('event_type', models.CharField(choices=[('group', 'Групповое'), ('individual', 'Индивидуальное'), ('homework', 'Домашнее задание'), ('review', 'Проверка работ')], default='group', max_length=20, verbose_name='Тип')),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], default='online', max_length=20, verbose_name='Формат')),
                ('telemost_url', models.URLField(blank=True, verbose_name='Ссылка Телемост')),
                ('audience', models.CharField(blank=True, max_length=200, verbose_name='Участники')),
                ('materials', models.TextField(blank=True, verbose_name='Материалы')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('done', 'Завершено'), ('cancelled', 'Отменено'), ('draft', 'Черновик')], default='planned', max_length=20, verbose_name='Статус')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Урок в расписании',
                'verbose_name_plural': 'Уроки в расписании',
                'ordering': ['starts_at'],
            },
        ),
    ]
