# Generated by Django 5.2.11 on 2026-06-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0003_profile_bio_profile_created_at_profile_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('css_background', models.TextField(help_text='Значение для CSS-свойства background', verbose_name='CSS фона')),
                ('text_tone', models.CharField(choices=[('dark', 'Тёмный'), ('light', 'Светлый')], default='dark', max_length=10, verbose_name='Тон текста')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'Фон интерактива',
                'verbose_name_plural': 'Фоны интерактивов',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveCardStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('css_class', models.CharField(help_text='Класс оформления карточек/полей в плеере', max_length=80, verbose_name='CSS-класс')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'Стиль карточек интерактива',
                'verbose_name_plural': 'Стили карточек интерактивов',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveSoundPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Профили звуков для flip/correct/wrong/tap', verbose_name='Настройки звуков')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'Звуковой пакет интерактива',
                'verbose_name_plural': 'Звуковые пакеты интерактивов',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='interactive',
            name='sound_enabled',
            field=models.BooleanField(default=True, verbose_name='Звук включён'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactives', to='Cabinet.interactivebackground', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='card_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactives', to='Cabinet.interactivecardstyle', verbose_name='Стиль карточек'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='sound_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactives', to='Cabinet.interactivesoundpack', verbose_name='Звуковой пакет'),
        ),
    ]
