# Generated by Django 5.2.11 on 2026-06-22 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0004_interactive_appearance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (подсказка)')),
                ('direction', models.CharField(choices=[('oge', 'ОГЭ'), ('ege', 'ЕГЭ'), ('python', 'Python'), ('school', 'Школьная база'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Направление')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Класс')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Сообщение ученику')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('expired', 'Истекло'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Приглашение ученика',
                'verbose_name_plural': 'Приглашения учеников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Привязанный зарегистрированный пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_rosters', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт ученика'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('teacher', 'user'), name='cabinet_unique_teacher_student_user'),
        ),
        migrations.AddField(
            model_name='studentinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Принял'),
        ),
        migrations.AddField(
            model_name='studentinvitation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='Cabinet.studentgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='studentinvitation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
