# Generated by Django 5.2.11 on 2026-06-22 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0005_student_invitations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='is_recurring_instance',
            field=models.BooleanField(default=False, verbose_name='Экземпляр серии'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='original_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Исходное начало'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='reminder_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='За сколько минут до урока напомнить', null=True, verbose_name='Напоминание (мин)'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'В кабинете'), ('email', 'Email'), ('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('sms', 'SMS')], default='in_app', max_length=16, verbose_name='Канал')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=16, verbose_name='Статус')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Cabinet.student', verbose_name='Ученик')),
                ('recipient_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='В кабинете')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Email')),
                ('vk_enabled', models.BooleanField(default=False, verbose_name='ВКонтакте')),
                ('vk_user_id', models.CharField(blank=True, max_length=32, verbose_name='VK user id')),
                ('notify_lesson_created', models.BooleanField(default=True)),
                ('notify_lesson_moved', models.BooleanField(default=True)),
                ('notify_lesson_cancelled', models.BooleanField(default=True)),
                ('notify_lesson_updated', models.BooleanField(default=True)),
                ('notify_participants_changed', models.BooleanField(default=True)),
                ('notify_before_lesson_minutes', models.PositiveSmallIntegerField(blank=True, default=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organizer', 'Организатор'), ('student', 'Ученик'), ('parent', 'Родитель'), ('guest', 'Гость')], default='student', max_length=20, verbose_name='Роль')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('vk_user_id', models.CharField(blank=True, max_length=32, verbose_name='VK user id')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='Уведомления')),
                ('status', models.CharField(choices=[('invited', 'Приглашён'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('removed', 'Удалён')], default='invited', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Cabinet.scheduleevent', verbose_name='Событие')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_participations', to='Cabinet.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_organizer_participations', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник занятия',
                'verbose_name_plural': 'Участники занятий',
                'ordering': ['role', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('individual_lesson', 'Индивидуальный урок'), ('group_lesson', 'Групповой урок'), ('consultation', 'Консультация'), ('homework_deadline', 'Дедлайн ДЗ'), ('review', 'Проверка работ'), ('other', 'Другое')], default='group_lesson', max_length=24, verbose_name='Тип')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс')),
                ('start_date', models.DateField(verbose_name='Дата первого занятия')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('recurrence_type', models.CharField(choices=[('none', 'Не повторять'), ('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('weekdays', 'По будням'), ('custom_weekdays', 'По выбранным дням'), ('biweekly', 'Каждые 2 недели'), ('monthly', 'Каждый месяц'), ('custom', 'Настроить вручную')], default='none', max_length=24, verbose_name='Периодичность')),
                ('recurrence_interval', models.PositiveSmallIntegerField(default=1, verbose_name='Интервал')),
                ('recurrence_weekdays', models.JSONField(blank=True, default=list, verbose_name='Дни недели')),
                ('recurrence_until', models.DateField(blank=True, null=True, verbose_name='Повторять до')),
                ('recurrence_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество занятий')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус')),
                ('meeting_url', models.URLField(blank=True, verbose_name='Ссылка на встречу')),
                ('meeting_provider', models.CharField(choices=[('yandex_telemost', 'Яндекс Телемост'), ('manual', 'Вручную'), ('none', 'Нет')], default='none', max_length=24, verbose_name='Провайдер встречи')),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], default='online', max_length=20, verbose_name='Формат')),
                ('topic', models.CharField(blank=True, max_length=500, verbose_name='Тема')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('reminder_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notify_on_create', models.BooleanField(default=True, verbose_name='Уведомить при создании')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_series', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_series', to='Cabinet.studentgroup', verbose_name='Группа')),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_series', to='Cabinet.homework', verbose_name='Домашнее задание')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_series', to='Cabinet.lesson', verbose_name='Урок')),
                ('lesson_plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_series', to='Cabinet.lessonplanitem', verbose_name='Пункт плана')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_series', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Серия занятий',
                'verbose_name_plural': 'Серии занятий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEventChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Создано'), ('moved', 'Перенесено'), ('cancelled', 'Отменено'), ('updated', 'Изменено'), ('participants_changed', 'Изменены участники'), ('restored', 'Восстановлено')], max_length=32, verbose_name='Тип изменения')),
                ('old_data', models.JSONField(blank=True, default=dict, verbose_name='Было')),
                ('new_data', models.JSONField(blank=True, default=dict, verbose_name='Стало')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='Cabinet.scheduleevent', verbose_name='Событие')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='Cabinet.scheduleeventseries', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'История изменения',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='Cabinet.scheduleeventseries', verbose_name='Серия'),
        ),
        migrations.CreateModel(
            name='EventReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_minutes', models.PositiveSmallIntegerField(verbose_name='За сколько минут')),
                ('channel', models.CharField(choices=[('in_app', 'В кабинете'), ('email', 'Email'), ('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('sms', 'SMS')], default='in_app', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='Cabinet.scheduleevent', verbose_name='Событие')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Лог напоминания',
                'verbose_name_plural': 'Логи напоминаний',
                'unique_together': {('event', 'recipient', 'reminder_minutes', 'channel')},
            },
        ),
    ]
