# Generated by Django 5.2.11 on 2026-06-23 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0006_schedule_series_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_month', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена/месяц')),
                ('price_year', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена/год')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('max_students', models.PositiveIntegerField(default=5, verbose_name='Макс. учеников')),
                ('max_groups', models.PositiveIntegerField(default=2, verbose_name='Макс. групп')),
                ('max_lessons', models.PositiveIntegerField(default=10, verbose_name='Макс. уроков')),
                ('max_interactives', models.PositiveIntegerField(default=5, verbose_name='Макс. интерактивов')),
                ('ai_requests_monthly_limit', models.PositiveIntegerField(default=10, verbose_name='ИИ-запросы в месяц')),
                ('max_storage_mb', models.PositiveIntegerField(default=512, verbose_name='Хранилище МБ')),
                ('has_homework', models.BooleanField(default=True, verbose_name='Домашние задания')),
                ('has_review', models.BooleanField(default=True, verbose_name='Проверка работ')),
                ('has_basic_notifications', models.BooleanField(default=False, verbose_name='Базовые уведомления')),
                ('has_advanced_notifications', models.BooleanField(default=False, verbose_name='Расширенные уведомления')),
                ('has_extended_library', models.BooleanField(default=False, verbose_name='Расширенная библиотека')),
                ('has_multi_teacher', models.BooleanField(default=False, verbose_name='Несколько учителей')),
                ('has_team_roles', models.BooleanField(default=False, verbose_name='Роли в команде')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['sort_order', 'price_month'],
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, max_length=64, verbose_name='Тип запроса')),
                ('prompt', models.TextField(blank=True, verbose_name='Запрос')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('cost_units', models.PositiveSmallIntegerField(default=1, verbose_name='Стоимость (кредиты)')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('blocked', 'Заблокирован')], default='success', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Лог ИИ-запроса',
                'verbose_name_plural': 'Логи ИИ-запросов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('trial', 'Пробная'), ('expired', 'Истекла'), ('cancelled', 'Отменена'), ('pending', 'Ожидает')], default='active', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('billing_period', models.CharField(choices=[('month', 'Месяц'), ('year', 'Год')], default='month', max_length=10, verbose_name='Период')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Автопродление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='Cabinet.tariffplan', verbose_name='Тарифный план')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('provider', models.CharField(default='mock', max_length=50, verbose_name='Провайдер')),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, verbose_name='ID платежа провайдера')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Cabinet.teachersubscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('used_requests', models.PositiveIntegerField(default=0, verbose_name='Использовано запросов')),
                ('limit_requests', models.PositiveIntegerField(default=10, verbose_name='Лимит запросов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Использование ИИ',
                'verbose_name_plural': 'Использование ИИ',
                'unique_together': {('teacher', 'period_start')},
            },
        ),
    ]
