# Generated by Django 5.2.11 on 2026-06-23 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0007_tariff_subscription_ai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('percent', 'Скидка %'), ('fixed', 'Фиксированная скидка ₽'), ('free_months', 'Бесплатные месяцы')], default='percent', max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Процент (0–100), сумма ₽ или кол-во месяцев', max_digits=10, verbose_name='Значение скидки')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Пусто — без ограничений', null=True, verbose_name='Макс. активаций')),
                ('max_uses_per_user', models.PositiveSmallIntegerField(default=1, verbose_name='Макс. на пользователя')),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Использован раз')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание (внутр.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Пусто — применяется ко всем тарифам', related_name='promo_codes', to='Cabinet.tariffplan', verbose_name='Применимо к тарифам')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка применена')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Применён')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_usages', to='Cabinet.payment', verbose_name='Платёж')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='Cabinet.promocode', verbose_name='Промокод')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'ordering': ['-applied_at'],
            },
        ),
    ]
