# Generated by Django 5.2.11 on 2026-06-23 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0009_lesson_plan_grade_item_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Пусто — публичный план, доступный всем учителям', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='lessonplanitem',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Цель занятия'),
        ),
        migrations.AlterField(
            model_name='lessonplanitem',
            name='homework_description',
            field=models.TextField(blank=True, verbose_name='Материалы к ДЗ'),
        ),
        migrations.AlterField(
            model_name='lessonplanitem',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='plan_items', to='Cabinet.material', verbose_name='Прикреплённые материалы'),
        ),
    ]
