# Generated by Django 5.2.11 on 2026-06-23 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0010_lessonplan_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='format',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='student',
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество занятий'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Пусто — публичный план, доступный всем учителям', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='LessonPlanEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('individual', 'Индивидуальный'), ('group', 'Групповой')], default='individual', max_length=20, verbose_name='Формат')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('frequency', models.CharField(blank=True, help_text='Например: 2 раза в неделю', max_length=64, verbose_name='Частота занятий')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('paused', 'На паузе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_enrollments', to='Cabinet.studentgroup', verbose_name='Группа')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Cabinet.lessonplan', verbose_name='План уроков')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_enrollments', to='Cabinet.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Назначение плана',
                'verbose_name_plural': 'Назначения планов',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('student__isnull', False), ('group__isnull', False), _connector='OR'), name='enrollment_has_student_or_group')],
            },
        ),
    ]
