# Generated by Django 5.2.11 on 2026-06-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cabinet", "0014_homework_submission_result_payload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="Используется в URL: /cabinet/login?ref=КОД", max_length=64, unique=True, verbose_name="Код ссылки")),
                ("title", models.CharField(blank=True, max_length=120, verbose_name="Название")),
                ("reward_months", models.PositiveSmallIntegerField(default=3, verbose_name="Месяцев подписки")),
                ("max_registrations", models.PositiveIntegerField(blank=True, help_text="Пусто — без ограничений", null=True, verbose_name="Макс. регистраций")),
                ("registrations_count", models.PositiveIntegerField(default=0, editable=False, verbose_name="Регистраций")),
                ("valid_from", models.DateTimeField(blank=True, null=True, verbose_name="Действует с")),
                ("valid_until", models.DateTimeField(blank=True, null=True, verbose_name="Действует до")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Описание (внутр.)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="referral_links", to=settings.AUTH_USER_MODEL, verbose_name="Владелец")),
                ("reward_plan", models.ForeignKey(blank=True, help_text="Пусто — максимальный активный тариф", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="referral_links", to="Cabinet.tariffplan", verbose_name="Тариф при регистрации")),
            ],
            options={
                "verbose_name": "Реферальная ссылка",
                "verbose_name_plural": "Реферальные ссылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralLinkRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reward_months", models.PositiveSmallIntegerField(verbose_name="Выдано месяцев")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Подписка до")),
                ("registered_at", models.DateTimeField(auto_now_add=True, verbose_name="Зарегистрирован")),
                ("referral_link", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="Cabinet.referrallink", verbose_name="Реферальная ссылка")),
                ("reward_plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="referral_registrations", to="Cabinet.tariffplan", verbose_name="Выданный тариф")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="referral_registration", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Регистрация по реферальной ссылке",
                "verbose_name_plural": "Регистрации по реферальным ссылкам",
                "ordering": ["-registered_at"],
            },
        ),
    ]
