# Generated by Django 5.2.11 on 2026-07-09 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0022_interactive_item_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='interactive_type',
            field=models.CharField(choices=[('flashcards', 'Карточки'), ('matching', 'Сопоставление'), ('ordering', 'Собери порядок'), ('quiz', 'Викторина'), ('wheel', 'Случайное колесо')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='reward_plan',
            field=models.ForeignKey(blank=True, help_text='Пусто — тариф «Профи»', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_links', to='Cabinet.tariffplan', verbose_name='Тариф при регистрации'),
        ),
        migrations.AlterField(
            model_name='wheelsegment',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Баллы'),
        ),
        migrations.CreateModel(
            name='StudentTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator_task_id', models.IntegerField(db_index=True, verbose_name='ID задачи в банке')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдано')),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_entries', to='Cabinet.homework', verbose_name='ДЗ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='Cabinet.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'История выданных задач',
                'verbose_name_plural': 'История выданных задач',
                'unique_together': {('student', 'generator_task_id')},
            },
        ),
    ]
