# Generated by Django 5.2.11 on 2026-07-09 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0023_student_task_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMaterialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение для ученика')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_material_assignments', to='Cabinet.studentgroup', verbose_name='Группа')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_assignments', to='Cabinet.material', verbose_name='Материал')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_material_assignments', to='Cabinet.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_material_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Прямая выдача материала',
                'verbose_name_plural': 'Прямые выдачи материалов',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
