# Generated by Django 5.2.11 on 2026-07-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0024_directmaterialassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvitation',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя ученика'),
        ),
        migrations.AddField(
            model_name='studentinvitation',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия ученика'),
        ),
    ]
