# Generated by Django 5.2.11 on 2026-07-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0025_invitation_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvitation',
            name='pre_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='Cabinet.student', verbose_name='Предварительный профиль'),
        ),
    ]
