# Generated by Django 5.2.11 on 2026-07-19 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0026_invitation_pre_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='meeting_provider',
            field=models.CharField(choices=[('yandex_telemost', 'Яндекс Телемост'), ('jitsi', 'Jitsi Meet'), ('manual', 'Вручную'), ('none', 'Нет')], default='none', max_length=24, verbose_name='Провайдер встречи'),
        ),
        migrations.AlterField(
            model_name='scheduleeventseries',
            name='meeting_provider',
            field=models.CharField(choices=[('yandex_telemost', 'Яндекс Телемост'), ('jitsi', 'Jitsi Meet'), ('manual', 'Вручную'), ('none', 'Нет')], default='none', max_length=24, verbose_name='Провайдер встречи'),
        ),
        migrations.CreateModel(
            name='VideoMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('room_name', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Название комнаты')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('live', 'Идёт сейчас'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('actual_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало')),
                ('actual_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое завершение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_video_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('schedule_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_meeting', to='Cabinet.scheduleevent', verbose_name='Урок в расписании')),
            ],
            options={
                'verbose_name': 'Видеоконференция',
                'verbose_name_plural': 'Видеоконференции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(verbose_name='Вход')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Выход')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('jitsi_participant_id', models.CharField(blank=True, max_length=255, verbose_name='Jitsi participant id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendance_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='Cabinet.videomeeting', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Посещаемость видеоконференции',
                'verbose_name_plural': 'Посещаемость видеоконференций',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['meeting', 'user', 'left_at'], name='Cabinet_mee_meeting_0ba3cf_idx')],
            },
        ),
    ]
