# Generated by Django 5.2.11 on 2026-07-20 17:49

import Cabinet.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0027_video_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Новая доска', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('scene_data', models.JSONField(default=Cabinet.models.empty_board_scene, verbose_name='Данные сцены')),
                ('thumbnail', models.TextField(blank=True, verbose_name='Превью')),
                ('allow_export', models.BooleanField(default=True, verbose_name='Разрешить экспорт зрителям')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_boards', to='Cabinet.studentgroup', verbose_name='Группа')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_boards', to='Cabinet.lesson', verbose_name='Урок')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_boards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('schedule_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_boards', to='Cabinet.scheduleevent', verbose_name='Событие расписания')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_boards', to='Cabinet.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Интерактивная доска',
                'verbose_name_plural': 'Интерактивные доски',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveBoardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], default='view', max_length=10, verbose_name='Право')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='Cabinet.interactiveboard', verbose_name='Доска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_board_access', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к интерактивной доске',
                'verbose_name_plural': 'Доступы к интерактивным доскам',
            },
        ),
        migrations.CreateModel(
            name='InteractiveBoardAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cabinet/boards/%Y/%m/', verbose_name='Файл')),
                ('mime_type', models.CharField(blank=True, max_length=64, verbose_name='MIME-тип')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Размер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='Cabinet.interactiveboard', verbose_name='Доска')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_board_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл интерактивной доски',
                'verbose_name_plural': 'Файлы интерактивных досок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interactiveboard',
            index=models.Index(fields=['owner', '-updated_at'], name='Cabinet_int_owner_i_8e0d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiveboard',
            index=models.Index(fields=['group'], name='Cabinet_int_group_i_69fe20_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiveboard',
            index=models.Index(fields=['student'], name='Cabinet_int_student_5b3f52_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiveboard',
            index=models.Index(fields=['lesson'], name='Cabinet_int_lesson__d651dc_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiveboard',
            index=models.Index(fields=['schedule_event'], name='Cabinet_int_schedul_0f8f3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='interactiveboardaccess',
            constraint=models.UniqueConstraint(fields=('board', 'user'), name='unique_interactive_board_user_access'),
        ),
    ]
