# Generated by Django 5.2.11 on 2026-07-20 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0028_interactive_boards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnectToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Токен подключения Telegram',
                'verbose_name_plural': 'Токены подключения Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(default=19, help_text='Час локального времени (0–23) для сводки в Telegram', verbose_name='Час ежедневной сводки'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_homework',
            field=models.BooleanField(default=True, verbose_name='Напоминания о заданиях'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_review',
            field=models.BooleanField(default=True, verbose_name='Уведомления о проверке'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Telegram chat id'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telegram подключён'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram username'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_chat_id', ''), _negated=True), fields=('telegram_chat_id',), name='cabinet_unique_telegram_chat_id'),
        ),
        migrations.AddField(
            model_name='telegramconnecttoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connect_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
