# Generated by Django 5.2.11 on 2026-07-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0031_lesson_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакт')),
                ('role', models.CharField(blank=True, max_length=64, verbose_name='Кто вы')),
                ('teaches', models.CharField(blank=True, max_length=500, verbose_name='Чему учите')),
                ('help_topics', models.JSONField(blank=True, default=list, verbose_name='Чем можете помочь')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('materials_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на материалы')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Заявка учителя',
                'verbose_name_plural': 'Заявки учителей',
                'ordering': ['-created_at'],
            },
        ),
    ]
