# Generated by Django 5.2.11 on 2026-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0034_student_lesson_record_variant_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpackage',
            name='lesson_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Длительность одного занятия в минутах (для подсказки и фильтрации)', null=True),
        ),
    ]
