# Generated by Django 5.2.11 on 2026-07-21 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0035_package_lesson_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя')),
                ('display_name', models.CharField(max_length=255, verbose_name='Отображаемое имя')),
                ('storage_key', models.CharField(max_length=512, verbose_name='Ключ хранилища')),
                ('mime_type', models.CharField(blank=True, max_length=128, verbose_name='MIME-тип')),
                ('extension', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Расширение')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Checksum')),
                ('current_version', models.PositiveIntegerField(default=1, verbose_name='Текущая версия')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('trashed', 'В корзине')], db_index=True, default='active', max_length=16, verbose_name='Статус')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В избранном')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний доступ')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Файл кабинета',
                'verbose_name_plural': 'Файлы кабинета',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='cabinet_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='Cabinet.cabinetfile', verbose_name='Файл из хранилища'),
        ),
        migrations.CreateModel(
            name='CabinetFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В избранном')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_folders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Cabinet.cabinetfolder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка файлов',
                'verbose_name_plural': 'Папки файлов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CabinetFilePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('view', 'Только просмотр'), ('download', 'Просмотр и скачивание'), ('edit', 'Редактирование'), ('full', 'Полный доступ')], default='view', max_length=16, verbose_name='Уровень')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cabinet_file_permissions', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Cabinet.cabinetfile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_permissions', to='Cabinet.studentgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_permissions', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Cabinet.cabinetfolder')),
            ],
            options={
                'verbose_name': 'Право на файл',
                'verbose_name_plural': 'Права на файлы',
            },
        ),
        migrations.CreateModel(
            name='CabinetFileAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'Загрузка'), ('download', 'Скачивание'), ('rename', 'Переименование'), ('move', 'Перемещение'), ('copy', 'Копирование'), ('trash', 'Удаление в корзину'), ('restore', 'Восстановление'), ('purge', 'Окончательное удаление'), ('share', 'Выдача доступа'), ('unshare', 'Отзыв доступа'), ('version', 'Новая версия'), ('attach', 'Прикрепление'), ('detach', 'Открепление'), ('favorite', 'Избранное'), ('create_folder', 'Создание папки')], db_index=True, max_length=32, verbose_name='Действие')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_file_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='Cabinet.cabinetfile')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='Cabinet.cabinetfolder')),
            ],
            options={
                'verbose_name': 'Аудит файла',
                'verbose_name_plural': 'Аудит файлов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cabinetfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='Cabinet.cabinetfolder', verbose_name='Папка'),
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_bytes', models.PositiveBigIntegerField(blank=True, help_text='Пусто — значение из CABINET_FILE_STORAGE_QUOTA_BYTES', null=True, verbose_name='Лимит (байт)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Квота хранилища',
                'verbose_name_plural': 'Квоты хранилища',
            },
        ),
        migrations.CreateModel(
            name='CabinetFileRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('lesson', 'Урок'), ('plan_item', 'Пункт плана'), ('homework', 'Домашнее задание'), ('submission', 'Сдача ДЗ'), ('student', 'Ученик'), ('group', 'Группа'), ('board', 'Интерактивная доска'), ('material', 'Материал')], db_index=True, max_length=32, verbose_name='Тип связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_relations', to='Cabinet.interactiveboard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cabinet_file_relations', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='Cabinet.cabinetfile', verbose_name='Файл')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_relations', to='Cabinet.studentgroup')),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_relations', to='Cabinet.homework')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_relations', to='Cabinet.lesson')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_relations', to='Cabinet.material')),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_relations', to='Cabinet.lessonplanitem')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_relations', to='Cabinet.student')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_file_relations', to='Cabinet.homeworksubmission')),
            ],
            options={
                'verbose_name': 'Связь файла',
                'verbose_name_plural': 'Связи файлов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file', 'relation_type'], name='Cabinet_cab_file_id_a3a041_idx'), models.Index(fields=['lesson'], name='Cabinet_cab_lesson__9d515d_idx'), models.Index(fields=['plan_item'], name='Cabinet_cab_plan_it_98a09b_idx'), models.Index(fields=['homework'], name='Cabinet_cab_homewor_c02a15_idx'), models.Index(fields=['submission'], name='Cabinet_cab_submiss_0697c2_idx'), models.Index(fields=['student'], name='Cabinet_cab_student_fff6de_idx'), models.Index(fields=['group'], name='Cabinet_cab_group_i_a27853_idx'), models.Index(fields=['board'], name='Cabinet_cab_board_i_182015_idx')],
            },
        ),
        migrations.CreateModel(
            name='CabinetFileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('storage_key', models.CharField(max_length=512, verbose_name='Ключ хранилища')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='Cabinet.cabinetfile', verbose_name='Файл')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_file_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Версия файла',
                'verbose_name_plural': 'Версии файлов',
                'ordering': ['-version_number'],
                'unique_together': {('file', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='cabinetfolder',
            index=models.Index(fields=['owner', 'parent', 'deleted_at'], name='Cabinet_cab_owner_i_192e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfolder',
            index=models.Index(fields=['owner', 'name'], name='Cabinet_cab_owner_i_ef8ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfolder',
            index=models.Index(fields=['owner', 'updated_at'], name='Cabinet_cab_owner_i_3728ae_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfilepermission',
            index=models.Index(fields=['user', 'expires_at'], name='Cabinet_cab_user_id_c79adc_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfilepermission',
            index=models.Index(fields=['group', 'expires_at'], name='Cabinet_cab_group_i_ae691a_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfilepermission',
            index=models.Index(fields=['file'], name='Cabinet_cab_file_id_dcd765_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfilepermission',
            index=models.Index(fields=['folder'], name='Cabinet_cab_folder__305eba_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfile',
            index=models.Index(fields=['owner', 'folder', 'status'], name='Cabinet_cab_owner_i_8627b5_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfile',
            index=models.Index(fields=['owner', 'deleted_at'], name='Cabinet_cab_owner_i_ae8871_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfile',
            index=models.Index(fields=['owner', 'display_name'], name='Cabinet_cab_owner_i_6f0ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfile',
            index=models.Index(fields=['owner', 'updated_at'], name='Cabinet_cab_owner_i_4bbd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinetfile',
            index=models.Index(fields=['owner', 'is_favorite'], name='Cabinet_cab_owner_i_6ca29c_idx'),
        ),
    ]
