# Generated by Django 5.2.11 on 2026-07-23 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0036_cabinet_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Код предмета (как в планах: inf, math, prog, …)', max_length=32, verbose_name='Предмет')),
                ('title', models.CharField(blank=True, help_text='Например: ОГЭ, программирование, школьная программа', max_length=255, verbose_name='Название направления')),
                ('direction', models.CharField(blank=True, choices=[('oge', 'ОГЭ'), ('ege', 'ЕГЭ'), ('python', 'Python'), ('school', 'Школьная база'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Направление / уровень')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='Уровень')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Cabinet.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Предмет ученика',
                'verbose_name_plural': 'Предметы учеников',
                'ordering': ['subject', 'title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='directmaterialassignment',
            name='student_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_material_assignments', to='Cabinet.studentsubject', verbose_name='Предмет ученика'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='Cabinet.studentsubject', verbose_name='Предмет ученика'),
        ),
        migrations.AddField(
            model_name='lessonplanenrollment',
            name='student_subject',
            field=models.ForeignKey(blank=True, help_text='План назначается конкретному предмету ученика', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_enrollments', to='Cabinet.studentsubject', verbose_name='Предмет ученика'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='student_subject',
            field=models.ForeignKey(blank=True, help_text='Предмет занятия для индивидуального ученика', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='Cabinet.studentsubject', verbose_name='Предмет ученика'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='student_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_series', to='Cabinet.studentsubject', verbose_name='Предмет ученика'),
        ),
        migrations.AddConstraint(
            model_name='studentsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'subject', 'direction', 'title'), name='cabinet_unique_active_student_subject'),
        ),
    ]
