# Generated by Django 5.2.11 on 2026-07-23 05:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0037_student_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMaterialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resource_kind', models.CharField(help_text='pdf | presentation | image | text | workbook | interactive | cards | test | exercise | file | embed | notes | link', max_length=32, verbose_name='Тип ресурса')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('open_url', models.CharField(blank=True, default='', help_text='Относительный или проверенный URL без приватных путей файловой системы', max_length=1024, verbose_name='Безопасный URL открытия')),
                ('content_text', models.TextField(blank=True, default='', verbose_name='Текстовое содержимое')),
                ('interaction_mode', models.CharField(choices=[('view_only', 'Только просмотр'), ('collaborative', 'Совместное управление')], default='view_only', max_length=20, verbose_name='Режим взаимодействия')),
                ('collaborative_scope', models.CharField(choices=[('all', 'Все ученики'), ('selected', 'Выбранные ученики')], default='all', max_length=20, verbose_name='Кому разрешено совместное управление')),
                ('collaborative_user_ids', models.JSONField(blank=True, default=list, help_text='Используется при scope=selected; пустой список при scope=all означает всех учеников урока', verbose_name='User id с правом совместного управления')),
                ('current_state', models.JSONField(blank=True, default=dict, verbose_name='Состояние материала')),
                ('recent_operation_ids', models.JSONField(blank=True, default=list, verbose_name='Недавние operation_id (идемпотентность)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия состояния')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Открыта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('cabinet_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_sessions', to='Cabinet.cabinetfile', verbose_name='Файл хранилища')),
                ('interactive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_sessions', to='Cabinet.interactive', verbose_name='Интерактив')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_sessions', to='Cabinet.material', verbose_name='Материал')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_sessions', to='Cabinet.videomeeting', verbose_name='Видеоурок')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_meeting_material_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Открыл')),
            ],
            options={
                'verbose_name': 'Сессия материала видеоурока',
                'verbose_name_plural': 'Сессии материалов видеоурока',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMaterialWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('resource_kind', models.CharField(blank=True, default='', max_length=32, verbose_name='Тип ресурса')),
                ('state', models.JSONField(blank=True, default=dict, verbose_name='Итоговое состояние')),
                ('authors', models.JSONField(blank=True, default=list, verbose_name='Авторы изменений')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия на момент сохранения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_works', to='Cabinet.videomeeting', verbose_name='Видеоурок')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='Cabinet.meetingmaterialsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Результат работы с материалом урока',
                'verbose_name_plural': 'Результаты работы с материалами урока',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meetingmaterialsession',
            index=models.Index(fields=['meeting', 'is_active'], name='Cabinet_mee_meeting_5b7c90_idx'),
        ),
    ]
