# Generated by Django 5.2.11 on 2026-07-23 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0038_meeting_material_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCommunityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('review', 'Отзыв о платформе'), ('feature', 'Предложение новой функции'), ('bug', 'Сообщение об ошибке'), ('testing', 'Участие в тестировании'), ('development', 'Хочу помочь с разработкой'), ('methodology', 'Методическое сотрудничество'), ('other', 'Другое')], max_length=32, verbose_name='Тип обращения')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт')),
                ('subject_area', models.CharField(blank=True, max_length=200, verbose_name='Предмет / направление')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('reviewed', 'Просмотрено'), ('planned', 'В планах'), ('completed', 'Выполнено'), ('declined', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_community_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение сообщества учителей',
                'verbose_name_plural': 'Обращения сообщества учителей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feedback_type', 'status'], name='Cabinet_tea_feedbac_de9293_idx'), models.Index(fields=['-created_at'], name='Cabinet_tea_created_6b899c_idx')],
            },
        ),
    ]
