# Generated by Django 5.2.11 on 2026-07-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0044_student_notify_override'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='Cabinet_pus_user_id_59c45b_idx',
            old_name='Cabinet_pus_user_id_8f3a1b_idx',
        ),
        migrations.AlterField(
            model_name='eventreminderlog',
            name='channel',
            field=models.CharField(choices=[('in_app', 'В кабинете'), ('email', 'Email'), ('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('push', 'Web Push'), ('sms', 'SMS')], default='in_app', max_length=16),
        ),
    ]
