# Generated by Django 5.2.11 on 2026-08-02 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0046_homework_edit_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtransaction',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Историческая операция из миграции; не должна повторно менять остаток'),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='legacy_source_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='legacy_source_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='migration_batch_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='migration_key',
            field=models.CharField(blank=True, help_text='Уникальный ключ идемпотентной миграции', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='method',
            field=models.CharField(blank=True, choices=[('transfer', 'Перевод'), ('cash', 'Наличные'), ('card', 'Банковская карта'), ('sbp', 'СБП'), ('other', 'Другое'), ('legacy_payment', 'Оплачено по старой системе')], default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='billingtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('migration_key__isnull', False)), fields=('migration_key',), name='cabinet_unique_billing_tx_migration_key'),
        ),
    ]
