# Generated by Django 5.2.11 on 2026-08-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0047_billing_legacy_tx_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='created_from_review',
            field=models.BooleanField(default=False, verbose_name='Создано из проверки'),
        ),
        migrations.AddField(
            model_name='homework',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Защита от повторного создания при двойном запросе', max_length=128, null=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AddField(
            model_name='homework',
            name='source_homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_homeworks', to='Cabinet.homework', verbose_name='Исходное ДЗ'),
        ),
        migrations.AddField(
            model_name='homework',
            name='source_review_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_created_from_review', to='Cabinet.reviewitem', verbose_name='Исходная проверка'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('teacher', 'idempotency_key'), name='cabinet_unique_homework_teacher_idempotency'),
        ),
    ]
