# Generated by Django 5.2.11 on 2026-08-02 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0048_homework_from_review_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка'), ('gone', 'Подписка устарела'), ('skipped', 'Пропущено')], default='sent', max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='Ошибка')),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог доставки push',
                'verbose_name_plural': 'Логи доставки push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Автор действия'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, default='', help_text='Устойчивый ключ; пустая строка — без дедупликации', max_length=255, verbose_name='Ключ дедупликации'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Системный код из notification_catalog', max_length=64, verbose_name='Тип события'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user', 'is_read', 'channel'], name='Cabinet_not_recipie_be4116_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type', 'created_at'], name='Cabinet_not_event_t_48eebb_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key', ''), _negated=True), fields=('recipient_user', 'channel', 'event_key'), name='cabinet_notification_unique_event_key'),
        ),
        migrations.AddField(
            model_name='pushdeliverylog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_deliveries', to='Cabinet.notification', verbose_name='Уведомление'),
        ),
        migrations.AddField(
            model_name='pushdeliverylog',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='Cabinet.pushsubscription', verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='pushdeliverylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_delivery_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='pushdeliverylog',
            index=models.Index(fields=['user', 'created_at'], name='Cabinet_pus_user_id_940ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdeliverylog',
            index=models.Index(fields=['status', 'created_at'], name='Cabinet_pus_status_22ea95_idx'),
        ),
    ]
