# Generated by Django 5.2.11 on 2026-08-02 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0050_material_follow_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платёж подписки платформы', 'verbose_name_plural': 'Платежи подписки платформы'},
        ),
        migrations.AlterModelOptions(
            name='teachersubscription',
            options={'verbose_name': 'Подписка платформы', 'verbose_name_plural': 'Подписки платформы'},
        ),
        migrations.AddField(
            model_name='interactive',
            name='access_level',
            field=models.CharField(choices=[('free', 'Бесплатно'), ('teacher', 'Учитель'), ('professional', 'Профи'), ('premium', 'Премиум'), ('corporate', 'Корпоративный')], db_index=True, default='free', max_length=20, verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='new_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Новинка до'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='priority_release_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_interactives', to='Cabinet.tariffplan', verbose_name='Приоритетный тариф релиза'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='access_level',
            field=models.CharField(choices=[('free', 'Бесплатно'), ('teacher', 'Учитель'), ('professional', 'Профи'), ('premium', 'Премиум'), ('corporate', 'Корпоративный')], db_index=True, default='free', max_length=20, verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='new_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Новинка до'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='priority_release_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_lessons', to='Cabinet.tariffplan', verbose_name='Приоритетный тариф релиза'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='material',
            name='access_level',
            field=models.CharField(choices=[('free', 'Бесплатно'), ('teacher', 'Учитель'), ('professional', 'Профи'), ('premium', 'Премиум'), ('corporate', 'Корпоративный')], db_index=True, default='free', max_length=20, verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='material',
            name='new_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Новинка до'),
        ),
        migrations.AddField(
            model_name='material',
            name='priority_release_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_materials', to='Cabinet.tariffplan', verbose_name='Приоритетный тариф релиза'),
        ),
        migrations.AddField(
            model_name='material',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_period',
            field=models.CharField(choices=[('month', 'Месяц'), ('year', 'Год')], default='month', max_length=10, verbose_name='Период оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='payment',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая сумма'),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='Cabinet.tariffplan', verbose_name='Оплачиваемый тариф'),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Cabinet.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='bonus_days',
            field=models.PositiveIntegerField(default=0, help_text='Дополнительные дни доступа (можно комбинировать со скидкой)', verbose_name='Бонусные дни'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='first_payment_only',
            field=models.BooleanField(default=False, verbose_name='Только первый платёж'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='stackable_with_referral',
            field=models.BooleanField(default=False, verbose_name='Совмещается с рефералом'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='status',
            field=models.CharField(choices=[('reserved', 'Зарезервирован'), ('applied', 'Применён'), ('cancelled', 'Отменён')], default='applied', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Бейдж'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='content_access_rank',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=free, 1=teacher, 2=professional, 3=premium, 4=corporate', verbose_name='Ранг доступа к материалам'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='cta_type',
            field=models.CharField(choices=[('register', 'Регистрация'), ('checkout', 'Оплата'), ('contact', 'Оставить заявку')], default='checkout', max_length=20, verbose_name='Тип CTA'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='has_analytics',
            field=models.BooleanField(default=False, verbose_name='Расширенная аналитика'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='has_mass_actions',
            field=models.BooleanField(default=False, verbose_name='Массовые действия'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='has_priority_support',
            field=models.BooleanField(default=False, verbose_name='Приоритетная поддержка'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='has_simulators',
            field=models.BooleanField(default=False, verbose_name='Симуляторы'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Выделенный'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатный'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Показывать на витрине'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='max_variants_monthly',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто — без лимита', null=True, verbose_name='Лимит вариантов / мес'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='max_workbooks_monthly',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто — без лимита', null=True, verbose_name='Лимит рабочих тетрадей / мес'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='monthly_library_promise',
            field=models.BooleanField(default=False, help_text='«Не менее 5 новых материалов в месяц»', verbose_name='Обещание пополнения библиотеки'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменена'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец периода'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало периода'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='is_legacy_promo',
            field=models.BooleanField(default=False, verbose_name='Стартовая акция (legacy)'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='promo_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец промо'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='promo_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало промо'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='scheduled_change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата смены тарифа'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_subscriptions', to='Cabinet.tariffplan', verbose_name='Запланированный тариф'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='source',
            field=models.CharField(blank=True, choices=[('self', 'Самостоятельно'), ('launch_promo', 'Стартовая акция'), ('referral', 'Реферальная программа'), ('admin', 'Администратор'), ('payment', 'Оплата'), ('promo_code', 'Промокод')], default='self', max_length=32, verbose_name='Источник доступа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Скидка %'), ('fixed', 'Фиксированная скидка ₽'), ('free_months', 'Бесплатные месяцы'), ('bonus_days', 'Бонусные дни')], default='percent', max_length=20, verbose_name='Тип скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Процент (0–100), сумма ₽, кол-во месяцев или дней', max_digits=10, verbose_name='Значение скидки'),
        ),
        migrations.AlterField(
            model_name='teachersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('trial', 'Пробная'), ('expired', 'Истекла'), ('cancelled', 'Отменена'), ('pending', 'Ожидает'), ('past_due', 'Просрочена оплата'), ('suspended', 'Приостановлена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='AnonymousUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.UUIDField(db_index=True, unique=True, verbose_name='Anon ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64, verbose_name='Session key')),
                ('variants_created', models.PositiveIntegerField(default=0, verbose_name='Вариантов создано')),
                ('workbooks_created', models.PositiveIntegerField(default=0, verbose_name='Тетрадей создано')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_usage_records', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрированный пользователь')),
            ],
            options={
                'verbose_name': 'Анонимное использование',
                'verbose_name_plural': 'Анонимные использования',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_receipt_id', models.CharField(blank=True, max_length=255, verbose_name='ID чека у провайдера')),
                ('fiscal_number', models.CharField(blank=True, max_length=128, verbose_name='ФН / номер чека')),
                ('fiscal_document', models.CharField(blank=True, max_length=128, verbose_name='ФД')),
                ('fiscal_sign', models.CharField(blank=True, max_length=128, verbose_name='ФП')),
                ('receipt_url', models.URLField(blank=True, verbose_name='Ссылка на чек')),
                ('status', models.CharField(blank=True, default='pending', max_length=32, verbose_name='Статус')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='Cabinet.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Чек подписки',
                'verbose_name_plural': 'Чеки подписки',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50, verbose_name='Провайдер')),
                ('event_id', models.CharField(max_length=255, verbose_name='ID события')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='Cabinet.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Webhook платежа',
                'verbose_name_plural': 'Webhook платежи',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_months', models.PositiveSmallIntegerField(default=1, verbose_name='Месяцев награды')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('granted', 'Выдана'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards', to='Cabinet.payment', verbose_name='Платёж')),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_rewards', to='Cabinet.referrallink', verbose_name='Реферальная ссылка')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_triggered', to=settings.AUTH_USER_MODEL, verbose_name='Приглашённый')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_earned', to=settings.AUTH_USER_MODEL, verbose_name='Реферер')),
                ('reward_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_payment_rewards', to='Cabinet.tariffplan', verbose_name='Тариф награды')),
            ],
            options={
                'verbose_name': 'Реферальная награда за оплату',
                'verbose_name_plural': 'Реферальные награды за оплату',
                'ordering': ['-created_at'],
                'unique_together': {('referred_user', 'payment')},
            },
        ),
        migrations.CreateModel(
            name='TeacherMonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('variants_created', models.PositiveIntegerField(default=0, verbose_name='Вариантов создано')),
                ('workbooks_created', models.PositiveIntegerField(default=0, verbose_name='Тетрадей создано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage_records', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Месячное использование учителя',
                'verbose_name_plural': 'Месячные использования учителей',
                'unique_together': {('teacher', 'period_start')},
            },
        ),
    ]
