# Generated by Django 5.2.11 on 2026-08-02 17:00

import Cabinet.parent_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0052_remap_tariffs_and_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число попыток'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_payment_claim',
            field=models.BooleanField(default=True, verbose_name='Уведомление «родитель/ученик сообщил об оплате»'),
        ),
        migrations.AddField(
            model_name='studentlessonrecord',
            name='comment_visibility',
            field=models.CharField(choices=[('private_teacher', 'Только преподаватель'), ('student_only', 'Только ученик'), ('student_and_parent', 'Ученик и родитель')], default='student_only', help_text='Старые комментарии по умолчанию только ученику; родителю не открываются автоматически.', max_length=32, verbose_name='Видимость комментария'),
        ),
        migrations.AddField(
            model_name='teacherbillingsettings',
            name='show_billing_to_parent',
            field=models.BooleanField(default=False, help_text='По умолчанию выключено. Можно переопределить в приглашении родителя.', verbose_name='Показывать финансы родителю'),
        ),
        migrations.CreateModel(
            name='ParentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_name', models.CharField(blank=True, max_length=150, verbose_name='Имя родителя')),
                ('invited_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('invited_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('relationship_type', models.CharField(choices=[('mother', 'Мама'), ('father', 'Папа'), ('guardian', 'Опекун'), ('other', 'Другой представитель')], default='other', max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Хеш токена')),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='Короткий код')),
                ('status', models.CharField(choices=[('pending', 'Приглашение создано'), ('accepted', 'Доступ активен'), ('expired', 'Ссылка просрочена'), ('revoked', 'Приглашение отозвано')], db_index=True, default='pending', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=Cabinet.parent_models.default_parent_permissions, verbose_name='Разрешения')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_invitations_accepted', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invitations_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invitations', to='Cabinet.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Приглашение родителя',
                'verbose_name_plural': 'Приглашения родителей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Доступ активен'), ('revoked', 'Доступ отозван'), ('suspended', 'Временно отключён')], db_index=True, default='pending', max_length=20)),
                ('relationship_type', models.CharField(choices=[('mother', 'Мама'), ('father', 'Папа'), ('guardian', 'Опекун'), ('other', 'Другой представитель')], default='other', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=Cabinet.parent_models.default_parent_permissions, verbose_name='Разрешения')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='Cabinet.parentinvitation', verbose_name='Приглашение')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_relationships_created', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_children', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='Cabinet.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Связь родитель–ученик',
                'verbose_name_plural': 'Связи родитель–ученик',
            },
        ),
        migrations.CreateModel(
            name='ParentAccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_access_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_access_audit_logs', to='Cabinet.student')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='Cabinet.parentinvitation')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='Cabinet.parentstudentrelationship')),
            ],
            options={
                'verbose_name': 'Аудит доступа родителя',
                'verbose_name_plural': 'Аудит доступов родителей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Номер попытки')),
                ('status', models.CharField(choices=[('submitted', 'Сдано'), ('checked', 'Проверено'), ('returned', 'Возвращено'), ('needs_revision', 'Нужна доработка')], default='submitted', max_length=20, verbose_name='Статус')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Сдано')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('is_final', models.BooleanField(default=False, verbose_name='Итоговая на момент снимка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='Cabinet.homeworksubmission', verbose_name='Сдача')),
            ],
            options={
                'verbose_name': 'Попытка сдачи ДЗ',
                'verbose_name_plural': 'Попытки сдачи ДЗ',
                'ordering': ['submission_id', 'attempt_number'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'attempt_number'), name='cabinet_unique_homework_attempt_number')],
            },
        ),
        migrations.AddIndex(
            model_name='parentstudentrelationship',
            index=models.Index(fields=['parent', 'status'], name='Cabinet_par_parent__93e63f_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudentrelationship',
            index=models.Index(fields=['student', 'status'], name='Cabinet_par_student_c3ab3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentstudentrelationship',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='cabinet_unique_parent_student'),
        ),
    ]
