# Generated by Django 5.2.11 on 2026-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0053_parent_access_homework_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Автопродление'),
        ),
    ]
