# Generated by Django 5.2.11 on 2026-08-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0054_alter_teachersubscription_auto_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='content_source',
            field=models.CharField(choices=[('plan', 'Из плана обучения'), ('manual', 'Введено вручную'), ('mixed', 'Смешанный')], default='manual', max_length=16, verbose_name='Источник данных урока'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Цель урока'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='homework_description',
            field=models.TextField(blank=True, verbose_name='Домашнее задание'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='manual_override_fields',
            field=models.JSONField(blank=True, default=list, help_text='Список полей (topic, subtopic, description, goal), которые не синхронизируются из плана', verbose_name='Поля с ручным переопределением'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='plan_sync_enabled',
            field=models.BooleanField(default=True, help_text='Если выключено, изменения пункта плана не перезаписывают этот урок', verbose_name='Автообновление из плана обучения'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='plan_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация с планом'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='subtopic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подтема'),
        ),
        migrations.CreateModel(
            name='ScheduleEventMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('learning_plan', 'Из плана обучения'), ('lesson_manual', 'Только в уроке'), ('homework', 'Домашнее задание')], default='lesson_manual', max_length=20, verbose_name='Источник')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_materials', to='Cabinet.scheduleevent', verbose_name='Урок')),
                ('interactive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event_links', to='Cabinet.interactive', verbose_name='Интерактив')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event_links', to='Cabinet.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал урока расписания',
                'verbose_name_plural': 'Материалы уроков расписания',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('event', 'material', 'source'), name='uniq_event_material_source'), models.UniqueConstraint(condition=models.Q(('interactive__isnull', False)), fields=('event', 'interactive', 'source'), name='uniq_event_interactive_source')],
            },
        ),
    ]
