# Generated by Django 5.2.11 on 2026-08-03 20:27

import Cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0055_lesson_plan_content_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_error_message',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст ошибки'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='vapid_key_version',
            field=models.CharField(blank=True, default='', help_text='Короткий fingerprint публичного ключа на момент подписки', max_length=32, verbose_name='Версия VAPID'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='lesson_reminder_minutes',
            field=models.JSONField(blank=True, default=Cabinet.models.default_lesson_reminder_minutes, help_text='Список минут до урока. Пустой список — напоминания выключены.', verbose_name='Интервалы напоминаний (мин)'),
        ),
        migrations.AlterField(
            model_name='pushdeliverylog',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('gone', 'Подписка устарела'), ('skipped', 'Пропущено'), ('skipped_by_preferences', 'Отключено настройками'), ('deferred_by_quiet_hours', 'Отложено (тишина)'), ('invalid_subscription', 'Недействительная подписка')], default='sent', max_length=32),
        ),
    ]
