# Generated by Django 5.2.11 on 2026-08-04 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0059_interactive_item_image_charfields'),
        ('Generator', '0074_seasonal_themes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('auto', 'Автоматически'), ('default', 'Обычное оформление'), ('manual', 'Выбранная тема')], default='auto', max_length=16, verbose_name='Режим')),
                ('animations_enabled', models.BooleanField(default=True, verbose_name='Показывать анимацию')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('selected_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preferences', to='Generator.seasonaltheme', verbose_name='Выбранная тема')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_theme_preference', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки сезонного оформления',
                'verbose_name_plural': 'Настройки сезонного оформления',
            },
        ),
    ]
