# Generated by Django 5.2.11 on 2026-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0061_meeting_material_collab_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplanitem',
            name='topic',
            field=models.CharField(blank=True, help_text='500 симв. — совпадает с ScheduleEvent.topic/LessonJournal.planned_topic, чтобы синхронизация урок↔план↔журнал не обрезала тему.', max_length=500, verbose_name='Тема'),
        ),
    ]
