# Generated by Django 5.2.11 on 2026-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0062_lesson_plan_item_topic_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='manual_override_fields',
            field=models.JSONField(blank=True, default=list, help_text='Список полей (topic, subtopic, description, goal, homework_description), которые не синхронизируются из плана', verbose_name='Поля с ручным переопределением'),
        ),
    ]
