# Generated by Django 5.2.11 on 2026-08-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0063_alter_scheduleevent_manual_override_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermonthlyusage',
            name='interactives_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Интерактивов создано'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='max_groups',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Пусто — без лимита', null=True, verbose_name='Макс. групп'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='max_interactives',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Пусто — без лимита', null=True, verbose_name='Лимит интерактивов / мес'),
        ),
    ]
