# Generated by Django 5.2.11 on 2026-08-09 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_referral_data(apps, schema_editor):
    """Закрыть 50% у уже плативших; оставить по одной награде на приглашённого."""
    ReferralLinkRegistration = apps.get_model("Cabinet", "ReferralLinkRegistration")
    ReferralReward = apps.get_model("Cabinet", "ReferralReward")
    Payment = apps.get_model("Cabinet", "Payment")

    paid_teacher_ids = set(
        Payment.objects.filter(status="paid").values_list("teacher_id", flat=True)
    )
    for reg in ReferralLinkRegistration.objects.all().iterator():
        if reg.user_id in paid_teacher_ids:
            reg.invitee_discount_eligible = False
            reg.save(update_fields=["invitee_discount_eligible"])

    seen = set()
    for reward in ReferralReward.objects.order_by("id"):
        key = (reward.referred_user_id, getattr(reward, "reward_type", None) or "first_payment_days")
        if key in seen:
            reward.delete()
        else:
            seen.add(key)
            if not getattr(reward, "reward_days", None):
                reward.reward_days = 14
                reward.save(update_fields=["reward_days"])


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0064_tariff_limits_monthly_interactives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referralreward',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='referrallinkregistration',
            name='invitee_discount_eligible',
            field=models.BooleanField(default=True, help_text='False после первой успешной платной покупки подписки', verbose_name='Скидка доступна'),
        ),
        migrations.AddField(
            model_name='referrallinkregistration',
            name='invitee_discount_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_discount_registrations', to='Cabinet.payment', verbose_name='Платёж, закрывший скидку'),
        ),
        migrations.AddField(
            model_name='referrallinkregistration',
            name='invitee_discount_percent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Скидка приглашённому %'),
        ),
        migrations.AddField(
            model_name='referrallinkregistration',
            name='invitee_discount_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Скидка использована / закрыта'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Применена к подписке'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='reward_days',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='Дней награды'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='reward_type',
            field=models.CharField(choices=[('first_payment_days', 'Дни за первую оплату')], default='first_payment_days', max_length=40, verbose_name='Тип награды'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='reward_months',
            field=models.PositiveSmallIntegerField(default=0, help_text='Legacy. Новая программа: 50% приглашённому и +14 дней рефереру.', verbose_name='Месяцев (legacy)'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='reward_plan',
            field=models.ForeignKey(blank=True, help_text='Больше не выдаётся при регистрации. Оставлено для совместимости.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_links', to='Cabinet.tariffplan', verbose_name='Тариф (legacy)'),
        ),
        migrations.AlterField(
            model_name='referrallinkregistration',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписка до (legacy)'),
        ),
        migrations.AlterField(
            model_name='referrallinkregistration',
            name='reward_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Выдано месяцев (legacy)'),
        ),
        migrations.AlterField(
            model_name='referrallinkregistration',
            name='reward_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_registrations', to='Cabinet.tariffplan', verbose_name='Выданный тариф (legacy)'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Создана/начислена'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards', to='Cabinet.payment', verbose_name='Платёж-источник'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='reward_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Месяцев награды (legacy)'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='reward_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_payment_rewards', to='Cabinet.tariffplan', verbose_name='Тариф награды (legacy)'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('available', 'Доступен (отложен)'), ('granted', 'Применён'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.RunPython(forwards_referral_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='promocodeusage',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False), ('status', 'applied')), fields=('payment',), name='uniq_promo_usage_applied_payment'),
        ),
        migrations.AddConstraint(
            model_name='referralreward',
            constraint=models.UniqueConstraint(fields=('referred_user', 'reward_type'), name='uniq_referral_reward_referred_type'),
        ),
        migrations.AddConstraint(
            model_name='referralreward',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment',), name='uniq_referral_reward_payment'),
        ),
    ]
