# Generated by Django 5.2.11 on 2026-08-09 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0065_referral_promo_rewrite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='CustomerKey'),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Код ошибки'),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Описание ошибки'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_recurrent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рекуррентный (автопродление)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='OrderId'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rebill_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='RebillId'),
        ),
        migrations.AddField(
            model_name='payment',
            name='referral_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Реферальная скидка'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='last_renewal_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка автопродления'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='last_renewal_error',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ошибка автопродления'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='payment_method_mask',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Маска карты (от провайдера)'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='tbank_customer_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='T-Bank CustomerKey'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='tbank_rebill_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='T-Bank RebillId'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='cab_pay_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['teacher', 'status'], name='cab_pay_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubscription',
            index=models.Index(fields=['status', 'expires_at'], name='cab_sub_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubscription',
            index=models.Index(fields=['auto_renew', 'expires_at'], name='cab_sub_autorenew_exp_idx'),
        ),
    ]
