# Generated by Django 5.2.11 on 2026-08-09 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0066_payment_recurrent_and_subscription_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubscription',
            name='prepaid_until',
            field=models.DateTimeField(blank=True, help_text='После scheduled_change_at тариф становится pending/prepaid без нового Charge', null=True, verbose_name='Предоплаченный период до'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('prepaid', 'Предоплачен'), ('applied', 'Применён'), ('canceled', 'Отменён'), ('superseded', 'Заменён')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('reason', models.CharField(choices=[('downgrade', 'Понижение тарифа'), ('cancel_to_start', 'Переход на Старт'), ('replace', 'Замена будущего тарифа'), ('manual', 'Ручная смена')], default='downgrade', max_length=32, verbose_name='Причина')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Запрошено')),
                ('effective_at', models.DateTimeField(db_index=True, verbose_name='Дата перехода')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Применено')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено')),
                ('selected_student_ids', models.JSONField(blank=True, default=list, verbose_name='Выбранные активные ученики')),
                ('selected_group_ids', models.JSONField(blank=True, default=list, verbose_name='Выбранные активные группы')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_changes_from', to='Cabinet.tariffplan', verbose_name='С тарифа')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_changes', to='Cabinet.payment', verbose_name='Предоплата следующего периода')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_changes', to='Cabinet.teachersubscription', verbose_name='Подписка')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_changes', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_changes_to', to='Cabinet.tariffplan', verbose_name='На тариф')),
            ],
            options={
                'verbose_name': 'Смена тарифа подписки',
                'verbose_name_plural': 'Смены тарифов подписки',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='cab_plan_chg_sub_status_idx'), models.Index(fields=['status', 'effective_at'], name='cab_plan_chg_status_eff_idx')],
            },
        ),
    ]
