# Generated by Django 5.2.11 on 2026-08-13 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cabinet", "0067_subscription_plan_change_downgrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkSubmissionAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="cabinet/homework/", verbose_name="Файл")),
                ("original_name", models.CharField(blank=True, max_length=255, verbose_name="Исходное имя")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachments",
                        to="Cabinet.homeworksubmission",
                        verbose_name="Сдача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл сдачи ДЗ",
                "verbose_name_plural": "Файлы сдачи ДЗ",
                "ordering": ["id"],
            },
        ),
    ]
