# Generated by Django 5.2.11 on 2026-08-13 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0068_homework_submission_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='promotion_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка по акции'),
        ),
        migrations.AlterField(
            model_name='teachersubscription',
            name='source',
            field=models.CharField(blank=True, choices=[('self', 'Самостоятельно'), ('launch_promo', 'Стартовая акция'), ('referral', 'Реферальная программа'), ('admin', 'Администратор'), ('payment', 'Оплата'), ('promo_code', 'Промокод'), ('promotion', 'Акция')], default='self', max_length=32, verbose_name='Источник доступа'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=160, verbose_name='Внутреннее название')),
                ('title', models.CharField(max_length=160, verbose_name='Публичный заголовок')),
                ('short_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('how_to_get', models.TextField(blank=True, default='', verbose_name='Как получить')),
                ('terms', models.TextField(blank=True, default='', verbose_name='Условия')),
                ('button_text', models.CharField(blank=True, default='Выбрать тариф', max_length=80, verbose_name='Текст кнопки')),
                ('benefit_type', models.CharField(choices=[('fixed_price', 'Фиксированная цена'), ('free_period', 'Бесплатный период')], default='fixed_price', max_length=20, verbose_name='Тип выгоды')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Для фиксированной цены. Обычная цена берётся с тарифа.', max_digits=10, null=True, verbose_name='Акционная цена')),
                ('free_months', models.PositiveSmallIntegerField(blank=True, help_text='Для бесплатного периода.', null=True, verbose_name='Бесплатных месяцев')),
                ('pricing_duration', models.CharField(choices=[('first_payment_only', 'Только первый период')], default='first_payment_only', max_length=32, verbose_name='Длительность цены')),
                ('starts_at', models.DateTimeField(verbose_name='Можно получить с')),
                ('ends_at', models.DateTimeField(verbose_name='Можно получить до')),
                ('display_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Показывать с')),
                ('display_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Показывать до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('eligibility_type', models.CharField(choices=[('all', 'Всем'), ('new_users', 'Новым пользователям'), ('existing_users', 'Уже покупавшим'), ('current_free_plan', 'На бесплатном тарифе'), ('current_paid_users', 'С платной подпиской'), ('specific_users', 'Выбранным пользователям')], default='all', max_length=32, verbose_name='Аудитория')),
                ('registered_from', models.DateTimeField(blank=True, null=True, verbose_name='Регистрация с')),
                ('registered_until', models.DateTimeField(blank=True, null=True, verbose_name='Регистрация до')),
                ('claim_mode', models.CharField(choices=[('automatic', 'Автоматически'), ('action_required', 'По кнопке')], default='automatic', max_length=20, verbose_name='Как получить')),
                ('allow_promo_codes', models.BooleanField(default=False, help_text='Если выключено, акционная цена уже финальная.', verbose_name='Совмещается с промокодом')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Пусто — без общего лимита. Считаются успешные и зарезервированные.', null=True, verbose_name='Макс. активаций')),
                ('max_redemptions_per_user', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Пусто — без ограничения на пользователя.', null=True, verbose_name='Макс. на пользователя')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Больше — важнее. При равенстве выбирается акция с меньшим id.', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('eligible_users', models.ManyToManyField(blank=True, related_name='targeted_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Выбранные пользователи')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='Cabinet.tariffplan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Cabinet.promotion', verbose_name='Акция'),
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена тарифа на момент покупки')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('benefit_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Тип выгоды')),
                ('free_months', models.PositiveSmallIntegerField(default=0, verbose_name='Бесплатных месяцев')),
                ('status', models.CharField(choices=[('reserved', 'Зарезервирована'), ('applied', 'Применена'), ('cancelled', 'Отменена')], db_index=True, default='reserved', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_redemptions', to='Cabinet.payment', verbose_name='Платёж')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_redemptions', to='Cabinet.tariffplan', verbose_name='Тариф')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='Cabinet.promotion', verbose_name='Акция')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_redemptions', to='Cabinet.teachersubscription', verbose_name='Подписка')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Использование акции',
                'verbose_name_plural': 'Использования акций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='cab_promo_active_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['plan', 'is_active'], name='cab_promo_plan_active_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['promotion', 'status'], name='cab_promored_promo_st_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['teacher', 'promotion'], name='cab_promored_user_promo_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotionredemption',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False), ('status', 'applied')), fields=('payment',), name='uniq_promo_redemption_applied_payment'),
        ),
    ]
