# Generated by Django 5.2.11 on 2026-08-13 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0069_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaterialFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_folders', to='Cabinet.student', verbose_name='Ученик')),
                ('student_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_folders', to='Cabinet.studentsubject', verbose_name='Предмет ученика')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_material_folders', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Папка материалов ученика',
                'verbose_name_plural': 'Папки материалов ученика',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentMaterialPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_key', models.CharField(max_length=64, verbose_name='Ключ в библиотеке')),
                ('source', models.CharField(blank=True, max_length=20, verbose_name='Источник')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='Cabinet.studentmaterialfolder', verbose_name='Папка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_placements', to='Cabinet.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_material_placements', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Размещение материала ученика',
                'verbose_name_plural': 'Размещения материалов ученика',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='studentmaterialfolder',
            index=models.Index(fields=['teacher', 'student'], name='Cabinet_stu_teacher_d43b80_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmaterialfolder',
            constraint=models.UniqueConstraint(fields=('teacher', 'student', 'name'), name='cabinet_unique_student_material_folder_name'),
        ),
        migrations.AddIndex(
            model_name='studentmaterialplacement',
            index=models.Index(fields=['teacher', 'student'], name='Cabinet_stu_teacher_afb726_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmaterialplacement',
            index=models.Index(fields=['folder'], name='Cabinet_stu_folder__a9542e_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmaterialplacement',
            constraint=models.UniqueConstraint(fields=('teacher', 'student', 'library_key'), name='cabinet_unique_student_material_placement'),
        ),
    ]
