# Generated by Django 5.2.11 on 2026-08-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0075_meeting_screenshare_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meetingscreensharesession',
            new_name='Cabinet_mee_meeting_a507c2_idx',
            old_name='Cabinet_mee_meeting_ss_idx',
        ),
    ]
