# Generated by Django 5.2.11 on 2026-08-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0085_remove_material_shop'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activationevent',
            new_name='Cabinet_act_user_id_7d47c8_idx',
            old_name='Cabinet_act_user_id_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='activationevent',
            new_name='Cabinet_act_event_n_0116cd_idx',
            old_name='Cabinet_act_event_n_time_idx',
        ),
    ]
