# Generated by Django 5.2.11 on 2026-09-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0099_seed_catalog_inf_ege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='subject',
            field=models.CharField(choices=[('informatics', 'Информатика'), ('math', 'Математика'), ('phys', 'Физика'), ('other', 'Другое')], default='informatics', max_length=20, verbose_name='Предмет'),
        ),
    ]
