# Generated by Django 5.2.11 on 2026-09-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0101_teacher_availability_booking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teacheravailability',
            new_name='Cabinet_tea_teacher_738c7a_idx',
            old_name='Cabinet_tea_teacher_6f3a21_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherbooking',
            new_name='Cabinet_tea_teacher_ccb90c_idx',
            old_name='Cabinet_tea_teacher_8c1e44_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherbooking',
            new_name='Cabinet_tea_student_6f6b85_idx',
            old_name='Cabinet_tea_student_9b2f11_idx',
        ),
    ]
