# Generated by Django 5.2.11 on 2026-09-06 17:50

from django.db import migrations, models


PLAN_VALUES = {
    "start": {
        "max_teacher_tasks": 20,
        "max_teacher_task_copies_monthly": 5,
        "max_teacher_task_collections": 2,
        "has_teacher_task_attachments": False,
        "has_teacher_task_bulk_import": False,
    },
    "teacher": {
        "max_teacher_tasks": 500,
        "max_teacher_task_copies_monthly": None,
        "max_teacher_task_collections": 10,
        "has_teacher_task_attachments": True,
        "has_teacher_task_bulk_import": False,
    },
    "pro": {
        "max_teacher_tasks": 5000,
        "max_teacher_task_copies_monthly": None,
        "max_teacher_task_collections": None,
        "has_teacher_task_attachments": True,
        "has_teacher_task_bulk_import": True,
    },
    "premium": {
        "max_teacher_tasks": None,
        "max_teacher_task_copies_monthly": None,
        "max_teacher_task_collections": None,
        "has_teacher_task_attachments": True,
        "has_teacher_task_bulk_import": True,
    },
    "school": {
        "max_teacher_tasks": None,
        "max_teacher_task_copies_monthly": None,
        "max_teacher_task_collections": None,
        "has_teacher_task_attachments": True,
        "has_teacher_task_bulk_import": True,
    },
}


def seed_teacher_task_entitlements(apps, schema_editor):
    TariffPlan = apps.get_model("Cabinet", "TariffPlan")
    for slug, fields in PLAN_VALUES.items():
        TariffPlan.objects.filter(slug=slug).update(**fields)


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("Cabinet", "0102_teacher_availability_index_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariffplan",
            name="has_teacher_task_attachments",
            field=models.BooleanField(default=False, verbose_name="Вложения в задачах банка"),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="has_teacher_task_bulk_import",
            field=models.BooleanField(default=False, verbose_name="Массовый импорт задач банка"),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="max_teacher_task_collections",
            field=models.PositiveIntegerField(
                blank=True,
                default=2,
                help_text="Зарезервировано. Пусто — без лимита.",
                null=True,
                verbose_name="Лимит коллекций банка учителя",
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="max_teacher_task_copies_monthly",
            field=models.PositiveIntegerField(
                blank=True,
                default=5,
                help_text="Пусто — без месячного лимита копирования.",
                null=True,
                verbose_name="Копий из общего банка / мес",
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="max_teacher_tasks",
            field=models.PositiveIntegerField(
                blank=True,
                default=20,
                help_text="Все неудалённые задачи банка, включая черновики и архив. Пусто — без лимита.",
                null=True,
                verbose_name="Лимит задач банка учителя",
            ),
        ),
        migrations.RunPython(seed_teacher_task_entitlements, noop),
    ]
