# Generated by Django 5.2.11 on 2026-09-11 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_ai_plan_limits(apps, schema_editor):
    TariffPlan = apps.get_model("Cabinet", "TariffPlan")
    limits = {
        "start": (20, 2, 5, 40, 6000, 2500),
        "teacher": (250, 25, 30, 500, 12000, 4000),
        "pro": (500, 50, 50, 1000, 16000, 5000),
        "premium": (1000, 100, 100, 2000, 20000, 6000),
        "school": (5000, 400, 200, 10000, 20000, 8000),
    }
    for slug, (text, images, day, credits, prompt, output) in limits.items():
        TariffPlan.objects.filter(slug=slug).update(
            ai_requests_monthly_limit=text,
            ai_images_monthly_limit=images,
            ai_text_requests_daily_limit=day,
            ai_credits_monthly_limit=credits,
            ai_max_prompt_chars=prompt,
            ai_max_output_tokens=output,
            is_ai_enabled=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0105_interactive_custom_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Система')], max_length=16, verbose_name='Роль')),
                ('content', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Сообщение ИИ',
                'verbose_name_plural': 'Сообщения ИИ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_limit_per_minute', models.PositiveSmallIntegerField(default=5, verbose_name='Запросов в минуту на пользователя')),
                ('image_concurrency', models.PositiveSmallIntegerField(default=2, verbose_name='Одновременных генераций изображений')),
                ('max_images_per_request', models.PositiveSmallIntegerField(default=5, verbose_name='Макс. изображений в одном запросе')),
                ('max_tasks_per_request', models.PositiveSmallIntegerField(default=12, verbose_name='Макс. заданий в одном запросе')),
                ('bulk_refuse_above', models.PositiveIntegerField(default=80, verbose_name='Отказ при запросе заданий больше')),
                ('context_message_limit', models.PositiveSmallIntegerField(default=12, verbose_name='Сообщений контекста')),
                ('credit_text', models.PositiveSmallIntegerField(default=1, verbose_name='Кредиты: обычный текст')),
                ('credit_text_long', models.PositiveSmallIntegerField(default=2, verbose_name='Кредиты: длинная генерация')),
                ('credit_text_bulk', models.PositiveSmallIntegerField(default=3, verbose_name='Кредиты: объёмная генерация')),
                ('credit_image', models.PositiveSmallIntegerField(default=10, verbose_name='Кредиты: изображение')),
                ('credit_image_edit', models.PositiveSmallIntegerField(default=10, verbose_name='Кредиты: редактирование изображения')),
                ('credit_image_analysis', models.PositiveSmallIntegerField(default=3, verbose_name='Кредиты: анализ изображения')),
                ('provider_daily_token_limit', models.PositiveIntegerField(default=2000000, verbose_name='Аварийный лимит токенов / день')),
                ('provider_daily_cost_limit', models.DecimalField(decimal_places=2, default=150, max_digits=12, verbose_name='Аварийный лимит стоимости / день')),
                ('provider_monthly_cost_limit', models.DecimalField(decimal_places=2, default=3000, max_digits=12, verbose_name='Аварийный лимит стоимости / месяц')),
                ('input_token_cost', models.DecimalField(decimal_places=6, default=0.03, max_digits=10, verbose_name='Стоимость 1k входных токенов')),
                ('output_token_cost', models.DecimalField(decimal_places=6, default=0.12, max_digits=10, verbose_name='Стоимость 1k выходных токенов')),
                ('image_cost', models.DecimalField(decimal_places=4, default=0.8, max_digits=10, verbose_name='Стоимость одного изображения')),
                ('is_globally_enabled', models.BooleanField(default=True, verbose_name='ИИ включён на платформе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки ИИ платформы',
                'verbose_name_plural': 'Настройки ИИ платформы',
            },
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='actual_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Факт. стоимость'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Оценка стоимости'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='image_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Изображений'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Входящие токены'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='intent',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Intent'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='model',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='operation_type',
            field=models.CharField(choices=[('TEXT_CHAT', 'Текстовый запрос'), ('TEXT_LONG_GENERATION', 'Длинная генерация'), ('TEXT_BULK_GENERATION', 'Объёмная генерация'), ('IMAGE_GENERATION', 'Генерация изображения'), ('IMAGE_EDIT', 'Редактирование изображения'), ('IMAGE_ANALYSIS', 'Анализ изображения'), ('OPEN', 'Открытие ассистента')], db_index=True, default='TEXT_CHAT', max_length=32, verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Исходящие токены'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Провайдер'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='provider_request_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ID запроса провайдера'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего токенов'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='limit_credits',
            field=models.PositiveIntegerField(default=40, verbose_name='Лимит кредитов'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='limit_images',
            field=models.PositiveIntegerField(default=2, verbose_name='Лимит изображений'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='used_credits',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано кредитов'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='used_images',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано изображений'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='used_text_today',
            field=models.PositiveIntegerField(default=0, verbose_name='Текстовых запросов сегодня'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='used_text_today_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата дневного счётчика'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='ai_allowed_models',
            field=models.JSONField(blank=True, default=list, help_text='Пустой список — модель по умолчанию из настроек платформы.', verbose_name='Разрешённые модели'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='ai_credits_monthly_limit',
            field=models.PositiveIntegerField(default=40, help_text='Внутренний потолок стоимости. 0 — не ограничивать кредитами.', verbose_name='ИИ-кредиты в месяц'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='ai_images_monthly_limit',
            field=models.PositiveIntegerField(default=2, verbose_name='ИИ-изображения в месяц'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='ai_max_output_tokens',
            field=models.PositiveIntegerField(default=2500, verbose_name='Макс. длина ответа (токены)'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='ai_max_prompt_chars',
            field=models.PositiveIntegerField(default=8000, verbose_name='Макс. длина запроса (символы)'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='ai_text_requests_daily_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='ИИ-запросы в день'),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='is_ai_enabled',
            field=models.BooleanField(default=True, verbose_name='ИИ включён на тарифе'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('blocked', 'Заблокирован'), ('reserved', 'Резерв'), ('canceled', 'Отменён')], default='success', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='aiusage',
            name='limit_requests',
            field=models.PositiveIntegerField(default=20, verbose_name='Лимит текстовых запросов'),
        ),
        migrations.AlterField(
            model_name='aiusage',
            name='used_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано текстовых запросов'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='ai_requests_monthly_limit',
            field=models.PositiveIntegerField(default=20, verbose_name='ИИ-запросы в месяц'),
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Название')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Краткое содержание')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее открытие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Диалог ИИ',
                'verbose_name_plural': 'Диалоги ИИ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='Cabinet.aiconversation', verbose_name='Диалог'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['teacher', 'created_at'], name='cab_ai_log_teacher_created'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['status', 'created_at'], name='cab_ai_log_status_created'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['operation_type', 'created_at'], name='cab_ai_log_op_created'),
        ),
        migrations.AddConstraint(
            model_name='airequestlog',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('teacher', 'idempotency_key'), name='cab_ai_log_idem_uniq'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Cabinet.aiconversation', verbose_name='Диалог'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='Cabinet.airequestlog', verbose_name='Событие usage'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['teacher', '-updated_at'], name='cab_ai_conv_teacher_upd'),
        ),
        migrations.RunPython(seed_ai_plan_limits, migrations.RunPython.noop),
    ]
