# Generated by Django 5.2.11 on 2026-09-14 10:14

import Cabinet.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def forwards_migrate_payload_attachments(apps, schema_editor):
    HomeworkSubmission = apps.get_model("Cabinet", "HomeworkSubmission")
    from Cabinet.homework_task_files import migrate_submission_payload_attachments
    from Cabinet.models import HomeworkSubmission as LiveSubmission
    import logging

    logger = logging.getLogger(__name__)
    for row in HomeworkSubmission.objects.all().iterator():
        live = LiveSubmission.objects.filter(pk=row.pk).first()
        if live is None:
            continue
        payload = live.result_payload if isinstance(live.result_payload, dict) else {}
        if not any(
            payload.get(key)
            for key in (
                "attachments_by_task_id",
                "attachments_by_number",
                "teacher_attachments_by_task_id",
                "teacher_attachments_by_number",
                "teacher_comment_attachments",
            )
        ):
            continue
        try:
            migrate_submission_payload_attachments(live)
        except Exception:
            logger.exception("homework attachment migrate skipped submission_id=%s", live.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0106_ai_assistant_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_key', models.CharField(db_index=True, help_text='Стабильный id задания варианта или PK HomeworkTask. Не номер и не URL.', max_length=255, verbose_name='Идентификатор задания')),
                ('task_number', models.CharField(blank=True, max_length=64, verbose_name='Номер задания (метаданные)')),
                ('owner_role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель')], max_length=16, verbose_name='Роль владельца')),
                ('attachment_type', models.CharField(choices=[('student_answer', 'Ответ ученика'), ('teacher_comment', 'Комментарий учителя'), ('teacher_checked_file', 'Проверенный файл'), ('notebook_source', 'Исходник тетради'), ('notebook_export', 'Экспорт тетради'), ('other', 'Другое')], default='student_answer', max_length=32, verbose_name='Тип вложения')),
                ('file', models.FileField(blank=True, max_length=1024, null=True, upload_to=Cabinet.models.homework_attachment_upload_to, verbose_name='Файл')),
                ('original_filename', models.CharField(blank=True, max_length=512, verbose_name='Исходное имя')),
                ('mime_type', models.CharField(blank=True, max_length=128, verbose_name='MIME')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('storage_path', models.CharField(blank=True, max_length=512, verbose_name='Путь в storage')),
                ('legacy_url', models.CharField(blank=True, max_length=1024, verbose_name='URL из старого JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_task_attachments', to='Cabinet.homework', verbose_name='Домашнее задание')),
                ('homework_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='Cabinet.homeworktask', verbose_name='Задание ДЗ')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_file_attachments', to='Cabinet.homeworksubmission', verbose_name='Сдача')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Вложение задания ДЗ',
                'verbose_name_plural': 'Вложения заданий ДЗ',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkNotebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_key', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор задания')),
                ('owner_role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель')], max_length=16, verbose_name='Роль владельца')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('returned', 'Отправлено ученику')], default='draft', max_length=20, verbose_name='Статус')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия draft')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_notebooks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('homework_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to='Cabinet.homeworktask', verbose_name='Задание ДЗ')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='Cabinet.homeworksubmission', verbose_name='Сдача')),
            ],
            options={
                'verbose_name': 'Тетрадь ДЗ',
                'verbose_name_plural': 'Тетради ДЗ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkNotebookPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='Номер страницы')),
                ('background_file', models.FileField(blank=True, max_length=1024, null=True, upload_to=Cabinet.models.homework_notebook_page_background_upload_to, verbose_name='Растр фона')),
                ('page_type', models.CharField(choices=[('attachment', 'Файл'), ('pdf_page', 'Страница PDF'), ('blank', 'Пустой лист')], default='blank', max_length=20, verbose_name='Тип страницы')),
                ('pdf_page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Страница PDF')),
                ('width', models.PositiveIntegerField(default=1000, verbose_name='Логическая ширина')),
                ('height', models.PositiveIntegerField(default=1414, verbose_name='Логическая высота')),
                ('state', models.JSONField(blank=True, default=dict, verbose_name='Состояние аннотаций')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='Cabinet.homeworknotebook', verbose_name='Тетрадь')),
                ('source_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_pages', to='Cabinet.homeworkattachment', verbose_name='Исходный файл')),
            ],
            options={
                'verbose_name': 'Страница тетради ДЗ',
                'verbose_name_plural': 'Страницы тетради ДЗ',
                'ordering': ['notebook_id', 'page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkNotebookRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('reason', models.CharField(choices=[('autosave', 'Автосохранение'), ('student_submit', 'Сдача ученика'), ('teacher_return', 'Проверка учителя'), ('manual_save', 'Ручное сохранение')], default='manual_save', max_length=32, verbose_name='Причина')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок')),
                ('export_file', models.FileField(blank=True, max_length=1024, null=True, upload_to=Cabinet.models.homework_notebook_export_upload_to, verbose_name='PDF-снимок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_notebook_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='Cabinet.homeworknotebook', verbose_name='Тетрадь')),
            ],
            options={
                'verbose_name': 'Ревизия тетради ДЗ',
                'verbose_name_plural': 'Ревизии тетради ДЗ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='homeworknotebook',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for', to='Cabinet.homeworknotebookrevision', verbose_name='Отправленная ученику ревизия'),
        ),
        migrations.AddIndex(
            model_name='homeworkattachment',
            index=models.Index(fields=['submission', 'task_key', 'owner_role', 'is_deleted'], name='cab_hw_att_sub_task_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworknotebookrevision',
            index=models.Index(fields=['notebook', 'version'], name='cab_hw_nb_rev_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworknotebook',
            constraint=models.UniqueConstraint(fields=('submission', 'task_key', 'owner_role'), name='cabinet_unique_homework_notebook_owner_task'),
        ),
        migrations.RunPython(forwards_migrate_payload_attachments, migrations.RunPython.noop),
    ]
