# Generated by Django 5.2.11 on 2026-09-21 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0108_homework_attachment_path_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherbooking',
            name='cabinet_unique_active_teacher_weekday_slot',
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='Весь день'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Для последующего расчёта дороги через карты.', max_digits=9, null=True, verbose_name='Широта места'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Для последующего расчёта дороги через карты.', max_digits=9, null=True, verbose_name='Долгота места'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='location_place_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID места в картографическом API'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='travel_after_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дорога после события, мин'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='travel_before_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дорога до события, мин'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='visibility',
            field=models.CharField(choices=[('public', 'Видно участникам'), ('private', 'Только преподавателю')], db_index=True, default='public', max_length=16, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='Весь день'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list, help_text='ISO-даты, для которых экземпляр не создаётся (занятые слоты серии).', verbose_name='Пропущенные даты серии'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта места'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота места'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='location_place_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID места в картографическом API'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='travel_after_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дорога после события, мин'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='travel_before_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дорога до события, мин'),
        ),
        migrations.AddField(
            model_name='scheduleeventseries',
            name='visibility',
            field=models.CharField(choices=[('public', 'Видно участникам'), ('private', 'Только преподавателю')], default='public', max_length=16, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='teacherbillingsettings',
            name='default_booking_until',
            field=models.DateField(blank=True, help_text='Если не задано, используется 27 декабря текущего учебного периода.', null=True, verbose_name='Повторять бронирования учеников до'),
        ),
        migrations.AddField(
            model_name='teacherbooking',
            name='recurrence_interval',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Интервал'),
        ),
        migrations.AddField(
            model_name='teacherbooking',
            name='recurrence_type',
            field=models.CharField(db_index=True, default='weekly', max_length=24, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='teacherbooking',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True, verbose_name='Повторять до'),
        ),
        migrations.AddField(
            model_name='teacherbooking',
            name='recurrence_weekdays',
            field=models.JSONField(blank=True, default=list, verbose_name='Дни недели'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='event_type',
            field=models.CharField(choices=[('group', 'Групповое'), ('individual', 'Индивидуальное'), ('homework', 'Домашнее задание'), ('review', 'Проверка работ'), ('individual_lesson', 'Индивидуальный урок'), ('group_lesson', 'Групповой урок'), ('homework_deadline', 'Дедлайн ДЗ'), ('personal', 'Личное'), ('blocked', 'Заблокированное время')], default='group', max_length=24, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='scheduleeventseries',
            name='event_type',
            field=models.CharField(choices=[('individual_lesson', 'Индивидуальный урок'), ('group_lesson', 'Групповой урок'), ('consultation', 'Консультация'), ('homework_deadline', 'Дедлайн ДЗ'), ('review', 'Проверка работ'), ('personal', 'Личное событие'), ('blocked', 'Заблокированное время'), ('other', 'Другое')], default='group_lesson', max_length=24, verbose_name='Тип'),
        ),
        migrations.AddConstraint(
            model_name='teacherbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('recurrence_type', 'weekly')), fields=('teacher', 'weekday', 'start_time'), name='cabinet_unique_active_teacher_weekday_slot'),
        ),
    ]
