# Generated by Django 5.2.11 on 2026-09-24 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0109_calendar_personal_events_travel_booking'),
        ('Generator', '0097_lesson_collections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Подписка'), ('material', 'Покупка материала'), ('lesson', 'Покупка готового урока'), ('collection', 'Покупка набора уроков')], db_index=True, default='subscription', max_length=20, verbose_name='Назначение'),
        ),
        migrations.CreateModel(
            name='CollectionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('payment', 'Оплата'), ('admin', 'Выдан вручную')], default='payment', max_length=20, verbose_name='Источник')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачена'), ('refunded', 'Возврат'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='Куплено')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Пусто — бессрочный доступ.', null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='Generator.lessoncollection', verbose_name='Набор')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_purchase', to='Cabinet.payment', verbose_name='Платёж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка набора уроков',
                'verbose_name_plural': 'Покупки наборов уроков',
                'ordering': ['-purchased_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cab_col_purch_user_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('user', 'collection'), name='cab_col_purchase_user_col_paid_uniq')],
            },
        ),
    ]
