# Generated by Django 5.2.11 on 2026-09-26 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0110_lesson_collections'),
        ('Generator', '0099_collection_files_variants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksheetAIPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default='default', max_length=32, unique=True, verbose_name='Код')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Стоимость AI-листа',
                'verbose_name_plural': 'Стоимость AI-листов',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('grade', models.CharField(blank=True, default='', max_length=16, verbose_name='Класс')),
                ('topic', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема')),
                ('subtopic', models.CharField(blank=True, default='', max_length=255, verbose_name='Подтема')),
                ('task_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип задания')),
                ('difficulty', models.CharField(blank=True, default='', max_length=32, verbose_name='Сложность')),
                ('kind', models.CharField(choices=[('structure', 'Структура задания'), ('fipi', 'Правила ФИПИ'), ('method', 'Методика'), ('answer', 'Правила ответа'), ('age', 'Возраст'), ('format', 'Формат'), ('example', 'Пример'), ('pitfall', 'Типичная ошибка'), ('general', 'Общее')], default='general', max_length=16, verbose_name='Вид')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Инструкция')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_instructions', to='Generator.level', verbose_name='Уровень')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_instructions', to='Generator.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Инструкция базы знаний',
                'verbose_name_plural': 'База знаний для генерации заданий',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetAIQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('breakdown', models.JSONField(blank=True, default=list, verbose_name='Расшифровка')),
                ('selected_tasks', models.JSONField(blank=True, default=list, verbose_name='Выбранные задания')),
                ('plan', models.JSONField(blank=True, default=dict, verbose_name='План')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('consumed', 'Использован'), ('expired', 'Истёк'), ('failed', 'Ошибка')], db_index=True, default='open', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_ai_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расчёт генерации листа',
                'verbose_name_plural': 'Расчёты генерации листов',
            },
        ),
        migrations.CreateModel(
            name='WorksheetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('blocks', models.JSONField(blank=True, default=list, verbose_name='Блоки')),
                ('form', models.JSONField(blank=True, default=dict, verbose_name='Параметры редактора')),
                ('design', models.JSONField(blank=True, default=dict, verbose_name='Оформление')),
                ('orientation', models.CharField(default='portrait', max_length=16, verbose_name='Ориентация')),
                ('margin_mm', models.PositiveSmallIntegerField(default=12, verbose_name='Поля, мм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_documents', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Рабочий лист',
                'verbose_name_plural': 'Рабочие листы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetAIGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True, verbose_name='Запрос преподавателя')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('selected_tasks', models.JSONField(blank=True, default=list, verbose_name='Задания из банка')),
                ('generated_tasks', models.JSONField(blank=True, default=list, verbose_name='Созданные задания')),
                ('knowledge_ids', models.JSONField(blank=True, default=list, verbose_name='Инструкции')),
                ('quoted_cost', models.PositiveIntegerField(default=0, verbose_name='Цена расчёта')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Списано')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='Модель')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('succeeded', 'Готово'), ('partial', 'Частично'), ('failed', 'Ошибка')], db_index=True, default='running', max_length=16, verbose_name='Статус')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=80, verbose_name='Ключ идемпотентности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_ai_generations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generation', to='Cabinet.worksheetaiquote', verbose_name='Расчёт')),
                ('worksheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to='Cabinet.worksheetdocument', verbose_name='Рабочий лист')),
            ],
            options={
                'verbose_name': 'AI-генерация рабочего листа',
                'verbose_name_plural': 'AI-генерации рабочих листов',
            },
        ),
        migrations.CreateModel(
            name='AITokenAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс AI-токенов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_token_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Баланс AI-токенов',
                'verbose_name_plural': 'Балансы AI-токенов',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='ai_token_balance_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='AITransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('operation_type', models.CharField(choices=[('credit', 'Начисление'), ('debit', 'Списание'), ('refund', 'Возврат'), ('admin_adjustment', 'Корректировка'), ('purchase', 'Покупка'), ('subscription_credit', 'Начисление по тарифу')], db_index=True, max_length=32, verbose_name='Операция')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('balance_before', models.PositiveIntegerField(verbose_name='Баланс до')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Баланс после')),
                ('status', models.CharField(choices=[('posted', 'Проведена'), ('void', 'Аннулирована')], db_index=True, default='posted', max_length=16, verbose_name='Статус')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=80, verbose_name='Ключ идемпотентности')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_token_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Cabinet.worksheetaigeneration', verbose_name='Генерация')),
            ],
            options={
                'verbose_name': 'Операция AI-токенов',
                'verbose_name_plural': 'Журнал AI-токенов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_tx_user_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='ai_tx_user_idem_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AITaskCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, default='', max_length=16, verbose_name='Класс')),
                ('topic', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема')),
                ('subtopic', models.CharField(blank=True, default='', max_length=255, verbose_name='Подтема')),
                ('difficulty', models.CharField(blank=True, default='standard', max_length=32, verbose_name='Сложность')),
                ('task_type', models.CharField(blank=True, default='short_answer', max_length=64, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Условие')),
                ('structured_content', models.JSONField(blank=True, default=dict, verbose_name='Структура')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('solution', models.TextField(blank=True, verbose_name='Решение')),
                ('skill', models.CharField(blank=True, default='', max_length=255, verbose_name='Навык')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('source', models.CharField(default='ai_generated', max_length=32, verbose_name='Источник')),
                ('review_status', models.CharField(choices=[('ai_generated', 'Создано AI'), ('pending_review', 'Ожидает проверки'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending_review', max_length=32, verbose_name='Статус проверки')),
                ('text_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Хеш условия')),
                ('knowledge_ids', models.JSONField(blank=True, default=list, verbose_name='Инструкции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_task_candidates', to='Generator.level', verbose_name='Уровень')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_task_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Автор запроса')),
                ('promoted_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_candidate_sources', to='Generator.task', verbose_name='Задача банка после одобрения')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_task_candidates', to='Generator.subject', verbose_name='Предмет')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='Cabinet.worksheetaigeneration', verbose_name='Генерация')),
            ],
            options={
                'verbose_name': 'AI-задание',
                'verbose_name_plural': 'AI-задания на проверке',
                'indexes': [models.Index(fields=['review_status', 'subject'], name='ai_cand_status_subj_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='worksheetaiquote',
            index=models.Index(fields=['user', 'status'], name='ws_quote_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheetdocument',
            index=models.Index(fields=['teacher', 'created_at'], name='ws_doc_teacher_created_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheetaigeneration',
            index=models.Index(fields=['user', 'created_at'], name='ws_gen_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='worksheetaigeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='ws_gen_user_idem_uniq'),
        ),
    ]
